
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ExamAnalytics` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ExamAnalytics
 * 
 */
export type ExamAnalyticsModel = runtime.Types.Result.DefaultSelection<Prisma.$ExamAnalyticsPayload>

export type AggregateExamAnalytics = {
  _count: ExamAnalyticsCountAggregateOutputType | null
  _avg: ExamAnalyticsAvgAggregateOutputType | null
  _sum: ExamAnalyticsSumAggregateOutputType | null
  _min: ExamAnalyticsMinAggregateOutputType | null
  _max: ExamAnalyticsMaxAggregateOutputType | null
}

export type ExamAnalyticsAvgAggregateOutputType = {
  totalStudents: number | null
  attemptedStudents: number | null
  participationRate: number | null
  averageScore: number | null
  averagePercentage: number | null
  highestScore: number | null
  lowestScore: number | null
  medianScore: number | null
  averageTimeTaken: number | null
  completionRate: number | null
}

export type ExamAnalyticsSumAggregateOutputType = {
  totalStudents: number | null
  attemptedStudents: number | null
  participationRate: number | null
  averageScore: number | null
  averagePercentage: number | null
  highestScore: number | null
  lowestScore: number | null
  medianScore: number | null
  averageTimeTaken: number | null
  completionRate: number | null
}

export type ExamAnalyticsMinAggregateOutputType = {
  id: string | null
  examId: string | null
  totalStudents: number | null
  attemptedStudents: number | null
  participationRate: number | null
  averageScore: number | null
  averagePercentage: number | null
  highestScore: number | null
  lowestScore: number | null
  medianScore: number | null
  averageTimeTaken: number | null
  completionRate: number | null
  lastCalculated: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExamAnalyticsMaxAggregateOutputType = {
  id: string | null
  examId: string | null
  totalStudents: number | null
  attemptedStudents: number | null
  participationRate: number | null
  averageScore: number | null
  averagePercentage: number | null
  highestScore: number | null
  lowestScore: number | null
  medianScore: number | null
  averageTimeTaken: number | null
  completionRate: number | null
  lastCalculated: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExamAnalyticsCountAggregateOutputType = {
  id: number
  examId: number
  totalStudents: number
  attemptedStudents: number
  participationRate: number
  averageScore: number
  averagePercentage: number
  highestScore: number
  lowestScore: number
  medianScore: number
  scoreDistribution: number
  gradeDistribution: number
  questionAnalysis: number
  topPerformers: number
  averageTimeTaken: number
  completionRate: number
  lastCalculated: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ExamAnalyticsAvgAggregateInputType = {
  totalStudents?: true
  attemptedStudents?: true
  participationRate?: true
  averageScore?: true
  averagePercentage?: true
  highestScore?: true
  lowestScore?: true
  medianScore?: true
  averageTimeTaken?: true
  completionRate?: true
}

export type ExamAnalyticsSumAggregateInputType = {
  totalStudents?: true
  attemptedStudents?: true
  participationRate?: true
  averageScore?: true
  averagePercentage?: true
  highestScore?: true
  lowestScore?: true
  medianScore?: true
  averageTimeTaken?: true
  completionRate?: true
}

export type ExamAnalyticsMinAggregateInputType = {
  id?: true
  examId?: true
  totalStudents?: true
  attemptedStudents?: true
  participationRate?: true
  averageScore?: true
  averagePercentage?: true
  highestScore?: true
  lowestScore?: true
  medianScore?: true
  averageTimeTaken?: true
  completionRate?: true
  lastCalculated?: true
  createdAt?: true
  updatedAt?: true
}

export type ExamAnalyticsMaxAggregateInputType = {
  id?: true
  examId?: true
  totalStudents?: true
  attemptedStudents?: true
  participationRate?: true
  averageScore?: true
  averagePercentage?: true
  highestScore?: true
  lowestScore?: true
  medianScore?: true
  averageTimeTaken?: true
  completionRate?: true
  lastCalculated?: true
  createdAt?: true
  updatedAt?: true
}

export type ExamAnalyticsCountAggregateInputType = {
  id?: true
  examId?: true
  totalStudents?: true
  attemptedStudents?: true
  participationRate?: true
  averageScore?: true
  averagePercentage?: true
  highestScore?: true
  lowestScore?: true
  medianScore?: true
  scoreDistribution?: true
  gradeDistribution?: true
  questionAnalysis?: true
  topPerformers?: true
  averageTimeTaken?: true
  completionRate?: true
  lastCalculated?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ExamAnalyticsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExamAnalytics to aggregate.
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExamAnalytics to fetch.
   */
  orderBy?: Prisma.ExamAnalyticsOrderByWithRelationInput | Prisma.ExamAnalyticsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExamAnalyticsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExamAnalytics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExamAnalytics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExamAnalytics
  **/
  _count?: true | ExamAnalyticsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExamAnalyticsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExamAnalyticsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExamAnalyticsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExamAnalyticsMaxAggregateInputType
}

export type GetExamAnalyticsAggregateType<T extends ExamAnalyticsAggregateArgs> = {
      [P in keyof T & keyof AggregateExamAnalytics]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExamAnalytics[P]>
    : Prisma.GetScalarType<T[P], AggregateExamAnalytics[P]>
}




export type ExamAnalyticsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExamAnalyticsWhereInput
  orderBy?: Prisma.ExamAnalyticsOrderByWithAggregationInput | Prisma.ExamAnalyticsOrderByWithAggregationInput[]
  by: Prisma.ExamAnalyticsScalarFieldEnum[] | Prisma.ExamAnalyticsScalarFieldEnum
  having?: Prisma.ExamAnalyticsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExamAnalyticsCountAggregateInputType | true
  _avg?: ExamAnalyticsAvgAggregateInputType
  _sum?: ExamAnalyticsSumAggregateInputType
  _min?: ExamAnalyticsMinAggregateInputType
  _max?: ExamAnalyticsMaxAggregateInputType
}

export type ExamAnalyticsGroupByOutputType = {
  id: string
  examId: string
  totalStudents: number
  attemptedStudents: number
  participationRate: number
  averageScore: number
  averagePercentage: number
  highestScore: number
  lowestScore: number
  medianScore: number
  scoreDistribution: runtime.JsonValue
  gradeDistribution: runtime.JsonValue
  questionAnalysis: runtime.JsonValue[]
  topPerformers: string[]
  averageTimeTaken: number
  completionRate: number
  lastCalculated: Date
  createdAt: Date
  updatedAt: Date
  _count: ExamAnalyticsCountAggregateOutputType | null
  _avg: ExamAnalyticsAvgAggregateOutputType | null
  _sum: ExamAnalyticsSumAggregateOutputType | null
  _min: ExamAnalyticsMinAggregateOutputType | null
  _max: ExamAnalyticsMaxAggregateOutputType | null
}

type GetExamAnalyticsGroupByPayload<T extends ExamAnalyticsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExamAnalyticsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExamAnalyticsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExamAnalyticsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExamAnalyticsGroupByOutputType[P]>
      }
    >
  >



export type ExamAnalyticsWhereInput = {
  AND?: Prisma.ExamAnalyticsWhereInput | Prisma.ExamAnalyticsWhereInput[]
  OR?: Prisma.ExamAnalyticsWhereInput[]
  NOT?: Prisma.ExamAnalyticsWhereInput | Prisma.ExamAnalyticsWhereInput[]
  id?: Prisma.StringFilter<"ExamAnalytics"> | string
  examId?: Prisma.StringFilter<"ExamAnalytics"> | string
  totalStudents?: Prisma.IntFilter<"ExamAnalytics"> | number
  attemptedStudents?: Prisma.IntFilter<"ExamAnalytics"> | number
  participationRate?: Prisma.FloatFilter<"ExamAnalytics"> | number
  averageScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  averagePercentage?: Prisma.FloatFilter<"ExamAnalytics"> | number
  highestScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  lowestScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  medianScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  scoreDistribution?: Prisma.JsonFilter<"ExamAnalytics">
  gradeDistribution?: Prisma.JsonFilter<"ExamAnalytics">
  questionAnalysis?: Prisma.JsonNullableListFilter<"ExamAnalytics">
  topPerformers?: Prisma.StringNullableListFilter<"ExamAnalytics">
  averageTimeTaken?: Prisma.FloatFilter<"ExamAnalytics"> | number
  completionRate?: Prisma.FloatFilter<"ExamAnalytics"> | number
  lastCalculated?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
}

export type ExamAnalyticsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  examId?: Prisma.SortOrder
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  scoreDistribution?: Prisma.SortOrder
  gradeDistribution?: Prisma.SortOrder
  questionAnalysis?: Prisma.SortOrder
  topPerformers?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
  lastCalculated?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExamAnalyticsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  examId?: string
  AND?: Prisma.ExamAnalyticsWhereInput | Prisma.ExamAnalyticsWhereInput[]
  OR?: Prisma.ExamAnalyticsWhereInput[]
  NOT?: Prisma.ExamAnalyticsWhereInput | Prisma.ExamAnalyticsWhereInput[]
  totalStudents?: Prisma.IntFilter<"ExamAnalytics"> | number
  attemptedStudents?: Prisma.IntFilter<"ExamAnalytics"> | number
  participationRate?: Prisma.FloatFilter<"ExamAnalytics"> | number
  averageScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  averagePercentage?: Prisma.FloatFilter<"ExamAnalytics"> | number
  highestScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  lowestScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  medianScore?: Prisma.FloatFilter<"ExamAnalytics"> | number
  scoreDistribution?: Prisma.JsonFilter<"ExamAnalytics">
  gradeDistribution?: Prisma.JsonFilter<"ExamAnalytics">
  questionAnalysis?: Prisma.JsonNullableListFilter<"ExamAnalytics">
  topPerformers?: Prisma.StringNullableListFilter<"ExamAnalytics">
  averageTimeTaken?: Prisma.FloatFilter<"ExamAnalytics"> | number
  completionRate?: Prisma.FloatFilter<"ExamAnalytics"> | number
  lastCalculated?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ExamAnalytics"> | Date | string
}, "id" | "examId">

export type ExamAnalyticsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  examId?: Prisma.SortOrder
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  scoreDistribution?: Prisma.SortOrder
  gradeDistribution?: Prisma.SortOrder
  questionAnalysis?: Prisma.SortOrder
  topPerformers?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
  lastCalculated?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ExamAnalyticsCountOrderByAggregateInput
  _avg?: Prisma.ExamAnalyticsAvgOrderByAggregateInput
  _max?: Prisma.ExamAnalyticsMaxOrderByAggregateInput
  _min?: Prisma.ExamAnalyticsMinOrderByAggregateInput
  _sum?: Prisma.ExamAnalyticsSumOrderByAggregateInput
}

export type ExamAnalyticsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExamAnalyticsScalarWhereWithAggregatesInput | Prisma.ExamAnalyticsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExamAnalyticsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExamAnalyticsScalarWhereWithAggregatesInput | Prisma.ExamAnalyticsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ExamAnalytics"> | string
  examId?: Prisma.StringWithAggregatesFilter<"ExamAnalytics"> | string
  totalStudents?: Prisma.IntWithAggregatesFilter<"ExamAnalytics"> | number
  attemptedStudents?: Prisma.IntWithAggregatesFilter<"ExamAnalytics"> | number
  participationRate?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  averageScore?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  averagePercentage?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  highestScore?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  lowestScore?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  medianScore?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  scoreDistribution?: Prisma.JsonWithAggregatesFilter<"ExamAnalytics">
  gradeDistribution?: Prisma.JsonWithAggregatesFilter<"ExamAnalytics">
  questionAnalysis?: Prisma.JsonNullableListFilter<"ExamAnalytics">
  topPerformers?: Prisma.StringNullableListFilter<"ExamAnalytics">
  averageTimeTaken?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  completionRate?: Prisma.FloatWithAggregatesFilter<"ExamAnalytics"> | number
  lastCalculated?: Prisma.DateTimeWithAggregatesFilter<"ExamAnalytics"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ExamAnalytics"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ExamAnalytics"> | Date | string
}

export type ExamAnalyticsCreateInput = {
  id?: string
  examId: string
  totalStudents?: number
  attemptedStudents?: number
  participationRate?: number
  averageScore?: number
  averagePercentage?: number
  highestScore?: number
  lowestScore?: number
  medianScore?: number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsCreatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsCreatetopPerformersInput | string[]
  averageTimeTaken?: number
  completionRate?: number
  lastCalculated?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExamAnalyticsUncheckedCreateInput = {
  id?: string
  examId: string
  totalStudents?: number
  attemptedStudents?: number
  participationRate?: number
  averageScore?: number
  averagePercentage?: number
  highestScore?: number
  lowestScore?: number
  medianScore?: number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsCreatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsCreatetopPerformersInput | string[]
  averageTimeTaken?: number
  completionRate?: number
  lastCalculated?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExamAnalyticsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  examId?: Prisma.StringFieldUpdateOperationsInput | string
  totalStudents?: Prisma.IntFieldUpdateOperationsInput | number
  attemptedStudents?: Prisma.IntFieldUpdateOperationsInput | number
  participationRate?: Prisma.FloatFieldUpdateOperationsInput | number
  averageScore?: Prisma.FloatFieldUpdateOperationsInput | number
  averagePercentage?: Prisma.FloatFieldUpdateOperationsInput | number
  highestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  lowestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  medianScore?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsUpdatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsUpdatetopPerformersInput | string[]
  averageTimeTaken?: Prisma.FloatFieldUpdateOperationsInput | number
  completionRate?: Prisma.FloatFieldUpdateOperationsInput | number
  lastCalculated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExamAnalyticsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  examId?: Prisma.StringFieldUpdateOperationsInput | string
  totalStudents?: Prisma.IntFieldUpdateOperationsInput | number
  attemptedStudents?: Prisma.IntFieldUpdateOperationsInput | number
  participationRate?: Prisma.FloatFieldUpdateOperationsInput | number
  averageScore?: Prisma.FloatFieldUpdateOperationsInput | number
  averagePercentage?: Prisma.FloatFieldUpdateOperationsInput | number
  highestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  lowestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  medianScore?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsUpdatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsUpdatetopPerformersInput | string[]
  averageTimeTaken?: Prisma.FloatFieldUpdateOperationsInput | number
  completionRate?: Prisma.FloatFieldUpdateOperationsInput | number
  lastCalculated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExamAnalyticsCreateManyInput = {
  id?: string
  examId: string
  totalStudents?: number
  attemptedStudents?: number
  participationRate?: number
  averageScore?: number
  averagePercentage?: number
  highestScore?: number
  lowestScore?: number
  medianScore?: number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsCreatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsCreatetopPerformersInput | string[]
  averageTimeTaken?: number
  completionRate?: number
  lastCalculated?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ExamAnalyticsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  examId?: Prisma.StringFieldUpdateOperationsInput | string
  totalStudents?: Prisma.IntFieldUpdateOperationsInput | number
  attemptedStudents?: Prisma.IntFieldUpdateOperationsInput | number
  participationRate?: Prisma.FloatFieldUpdateOperationsInput | number
  averageScore?: Prisma.FloatFieldUpdateOperationsInput | number
  averagePercentage?: Prisma.FloatFieldUpdateOperationsInput | number
  highestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  lowestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  medianScore?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsUpdatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsUpdatetopPerformersInput | string[]
  averageTimeTaken?: Prisma.FloatFieldUpdateOperationsInput | number
  completionRate?: Prisma.FloatFieldUpdateOperationsInput | number
  lastCalculated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExamAnalyticsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  examId?: Prisma.StringFieldUpdateOperationsInput | string
  totalStudents?: Prisma.IntFieldUpdateOperationsInput | number
  attemptedStudents?: Prisma.IntFieldUpdateOperationsInput | number
  participationRate?: Prisma.FloatFieldUpdateOperationsInput | number
  averageScore?: Prisma.FloatFieldUpdateOperationsInput | number
  averagePercentage?: Prisma.FloatFieldUpdateOperationsInput | number
  highestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  lowestScore?: Prisma.FloatFieldUpdateOperationsInput | number
  medianScore?: Prisma.FloatFieldUpdateOperationsInput | number
  scoreDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  gradeDistribution?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  questionAnalysis?: Prisma.ExamAnalyticsUpdatequestionAnalysisInput | runtime.InputJsonValue[]
  topPerformers?: Prisma.ExamAnalyticsUpdatetopPerformersInput | string[]
  averageTimeTaken?: Prisma.FloatFieldUpdateOperationsInput | number
  completionRate?: Prisma.FloatFieldUpdateOperationsInput | number
  lastCalculated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExamAnalyticsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  examId?: Prisma.SortOrder
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  scoreDistribution?: Prisma.SortOrder
  gradeDistribution?: Prisma.SortOrder
  questionAnalysis?: Prisma.SortOrder
  topPerformers?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
  lastCalculated?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExamAnalyticsAvgOrderByAggregateInput = {
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
}

export type ExamAnalyticsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  examId?: Prisma.SortOrder
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
  lastCalculated?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExamAnalyticsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  examId?: Prisma.SortOrder
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
  lastCalculated?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ExamAnalyticsSumOrderByAggregateInput = {
  totalStudents?: Prisma.SortOrder
  attemptedStudents?: Prisma.SortOrder
  participationRate?: Prisma.SortOrder
  averageScore?: Prisma.SortOrder
  averagePercentage?: Prisma.SortOrder
  highestScore?: Prisma.SortOrder
  lowestScore?: Prisma.SortOrder
  medianScore?: Prisma.SortOrder
  averageTimeTaken?: Prisma.SortOrder
  completionRate?: Prisma.SortOrder
}

export type ExamAnalyticsCreatequestionAnalysisInput = {
  set: runtime.InputJsonValue[]
}

export type ExamAnalyticsCreatetopPerformersInput = {
  set: string[]
}

export type ExamAnalyticsUpdatequestionAnalysisInput = {
  set?: runtime.InputJsonValue[]
  push?: runtime.InputJsonValue | runtime.InputJsonValue[]
}

export type ExamAnalyticsUpdatetopPerformersInput = {
  set?: string[]
  push?: string | string[]
}



export type ExamAnalyticsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  examId?: boolean
  totalStudents?: boolean
  attemptedStudents?: boolean
  participationRate?: boolean
  averageScore?: boolean
  averagePercentage?: boolean
  highestScore?: boolean
  lowestScore?: boolean
  medianScore?: boolean
  scoreDistribution?: boolean
  gradeDistribution?: boolean
  questionAnalysis?: boolean
  topPerformers?: boolean
  averageTimeTaken?: boolean
  completionRate?: boolean
  lastCalculated?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["examAnalytics"]>

export type ExamAnalyticsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  examId?: boolean
  totalStudents?: boolean
  attemptedStudents?: boolean
  participationRate?: boolean
  averageScore?: boolean
  averagePercentage?: boolean
  highestScore?: boolean
  lowestScore?: boolean
  medianScore?: boolean
  scoreDistribution?: boolean
  gradeDistribution?: boolean
  questionAnalysis?: boolean
  topPerformers?: boolean
  averageTimeTaken?: boolean
  completionRate?: boolean
  lastCalculated?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["examAnalytics"]>

export type ExamAnalyticsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  examId?: boolean
  totalStudents?: boolean
  attemptedStudents?: boolean
  participationRate?: boolean
  averageScore?: boolean
  averagePercentage?: boolean
  highestScore?: boolean
  lowestScore?: boolean
  medianScore?: boolean
  scoreDistribution?: boolean
  gradeDistribution?: boolean
  questionAnalysis?: boolean
  topPerformers?: boolean
  averageTimeTaken?: boolean
  completionRate?: boolean
  lastCalculated?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["examAnalytics"]>

export type ExamAnalyticsSelectScalar = {
  id?: boolean
  examId?: boolean
  totalStudents?: boolean
  attemptedStudents?: boolean
  participationRate?: boolean
  averageScore?: boolean
  averagePercentage?: boolean
  highestScore?: boolean
  lowestScore?: boolean
  medianScore?: boolean
  scoreDistribution?: boolean
  gradeDistribution?: boolean
  questionAnalysis?: boolean
  topPerformers?: boolean
  averageTimeTaken?: boolean
  completionRate?: boolean
  lastCalculated?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ExamAnalyticsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "examId" | "totalStudents" | "attemptedStudents" | "participationRate" | "averageScore" | "averagePercentage" | "highestScore" | "lowestScore" | "medianScore" | "scoreDistribution" | "gradeDistribution" | "questionAnalysis" | "topPerformers" | "averageTimeTaken" | "completionRate" | "lastCalculated" | "createdAt" | "updatedAt", ExtArgs["result"]["examAnalytics"]>

export type $ExamAnalyticsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExamAnalytics"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    examId: string
    totalStudents: number
    attemptedStudents: number
    participationRate: number
    averageScore: number
    averagePercentage: number
    highestScore: number
    lowestScore: number
    medianScore: number
    scoreDistribution: runtime.JsonValue
    gradeDistribution: runtime.JsonValue
    questionAnalysis: runtime.JsonValue[]
    topPerformers: string[]
    averageTimeTaken: number
    completionRate: number
    lastCalculated: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["examAnalytics"]>
  composites: {}
}

export type ExamAnalyticsGetPayload<S extends boolean | null | undefined | ExamAnalyticsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload, S>

export type ExamAnalyticsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExamAnalyticsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExamAnalyticsCountAggregateInputType | true
  }

export interface ExamAnalyticsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExamAnalytics'], meta: { name: 'ExamAnalytics' } }
  /**
   * Find zero or one ExamAnalytics that matches the filter.
   * @param {ExamAnalyticsFindUniqueArgs} args - Arguments to find a ExamAnalytics
   * @example
   * // Get one ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExamAnalyticsFindUniqueArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExamAnalytics that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExamAnalyticsFindUniqueOrThrowArgs} args - Arguments to find a ExamAnalytics
   * @example
   * // Get one ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExamAnalyticsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExamAnalytics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsFindFirstArgs} args - Arguments to find a ExamAnalytics
   * @example
   * // Get one ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExamAnalyticsFindFirstArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExamAnalytics that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsFindFirstOrThrowArgs} args - Arguments to find a ExamAnalytics
   * @example
   * // Get one ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExamAnalyticsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExamAnalytics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findMany()
   * 
   * // Get first 10 ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const examAnalyticsWithIdOnly = await prisma.examAnalytics.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExamAnalyticsFindManyArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExamAnalytics.
   * @param {ExamAnalyticsCreateArgs} args - Arguments to create a ExamAnalytics.
   * @example
   * // Create one ExamAnalytics
   * const ExamAnalytics = await prisma.examAnalytics.create({
   *   data: {
   *     // ... data to create a ExamAnalytics
   *   }
   * })
   * 
   */
  create<T extends ExamAnalyticsCreateArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsCreateArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExamAnalytics.
   * @param {ExamAnalyticsCreateManyArgs} args - Arguments to create many ExamAnalytics.
   * @example
   * // Create many ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExamAnalyticsCreateManyArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExamAnalytics and returns the data saved in the database.
   * @param {ExamAnalyticsCreateManyAndReturnArgs} args - Arguments to create many ExamAnalytics.
   * @example
   * // Create many ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExamAnalytics and only return the `id`
   * const examAnalyticsWithIdOnly = await prisma.examAnalytics.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExamAnalyticsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExamAnalytics.
   * @param {ExamAnalyticsDeleteArgs} args - Arguments to delete one ExamAnalytics.
   * @example
   * // Delete one ExamAnalytics
   * const ExamAnalytics = await prisma.examAnalytics.delete({
   *   where: {
   *     // ... filter to delete one ExamAnalytics
   *   }
   * })
   * 
   */
  delete<T extends ExamAnalyticsDeleteArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsDeleteArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExamAnalytics.
   * @param {ExamAnalyticsUpdateArgs} args - Arguments to update one ExamAnalytics.
   * @example
   * // Update one ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExamAnalyticsUpdateArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsUpdateArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExamAnalytics.
   * @param {ExamAnalyticsDeleteManyArgs} args - Arguments to filter ExamAnalytics to delete.
   * @example
   * // Delete a few ExamAnalytics
   * const { count } = await prisma.examAnalytics.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExamAnalyticsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExamAnalyticsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExamAnalytics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExamAnalyticsUpdateManyArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExamAnalytics and returns the data updated in the database.
   * @param {ExamAnalyticsUpdateManyAndReturnArgs} args - Arguments to update many ExamAnalytics.
   * @example
   * // Update many ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExamAnalytics and only return the `id`
   * const examAnalyticsWithIdOnly = await prisma.examAnalytics.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExamAnalyticsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExamAnalytics.
   * @param {ExamAnalyticsUpsertArgs} args - Arguments to update or create a ExamAnalytics.
   * @example
   * // Update or create a ExamAnalytics
   * const examAnalytics = await prisma.examAnalytics.upsert({
   *   create: {
   *     // ... data to create a ExamAnalytics
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExamAnalytics we want to update
   *   }
   * })
   */
  upsert<T extends ExamAnalyticsUpsertArgs>(args: Prisma.SelectSubset<T, ExamAnalyticsUpsertArgs<ExtArgs>>): Prisma.Prisma__ExamAnalyticsClient<runtime.Types.Result.GetResult<Prisma.$ExamAnalyticsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExamAnalytics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsCountArgs} args - Arguments to filter ExamAnalytics to count.
   * @example
   * // Count the number of ExamAnalytics
   * const count = await prisma.examAnalytics.count({
   *   where: {
   *     // ... the filter for the ExamAnalytics we want to count
   *   }
   * })
  **/
  count<T extends ExamAnalyticsCountArgs>(
    args?: Prisma.Subset<T, ExamAnalyticsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExamAnalyticsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExamAnalytics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExamAnalyticsAggregateArgs>(args: Prisma.Subset<T, ExamAnalyticsAggregateArgs>): Prisma.PrismaPromise<GetExamAnalyticsAggregateType<T>>

  /**
   * Group by ExamAnalytics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamAnalyticsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExamAnalyticsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExamAnalyticsGroupByArgs['orderBy'] }
      : { orderBy?: ExamAnalyticsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExamAnalyticsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExamAnalyticsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExamAnalytics model
 */
readonly fields: ExamAnalyticsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExamAnalytics.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExamAnalyticsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExamAnalytics model
 */
export interface ExamAnalyticsFieldRefs {
  readonly id: Prisma.FieldRef<"ExamAnalytics", 'String'>
  readonly examId: Prisma.FieldRef<"ExamAnalytics", 'String'>
  readonly totalStudents: Prisma.FieldRef<"ExamAnalytics", 'Int'>
  readonly attemptedStudents: Prisma.FieldRef<"ExamAnalytics", 'Int'>
  readonly participationRate: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly averageScore: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly averagePercentage: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly highestScore: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly lowestScore: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly medianScore: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly scoreDistribution: Prisma.FieldRef<"ExamAnalytics", 'Json'>
  readonly gradeDistribution: Prisma.FieldRef<"ExamAnalytics", 'Json'>
  readonly questionAnalysis: Prisma.FieldRef<"ExamAnalytics", 'Json[]'>
  readonly topPerformers: Prisma.FieldRef<"ExamAnalytics", 'String[]'>
  readonly averageTimeTaken: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly completionRate: Prisma.FieldRef<"ExamAnalytics", 'Float'>
  readonly lastCalculated: Prisma.FieldRef<"ExamAnalytics", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ExamAnalytics", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ExamAnalytics", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ExamAnalytics findUnique
 */
export type ExamAnalyticsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter, which ExamAnalytics to fetch.
   */
  where: Prisma.ExamAnalyticsWhereUniqueInput
}

/**
 * ExamAnalytics findUniqueOrThrow
 */
export type ExamAnalyticsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter, which ExamAnalytics to fetch.
   */
  where: Prisma.ExamAnalyticsWhereUniqueInput
}

/**
 * ExamAnalytics findFirst
 */
export type ExamAnalyticsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter, which ExamAnalytics to fetch.
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExamAnalytics to fetch.
   */
  orderBy?: Prisma.ExamAnalyticsOrderByWithRelationInput | Prisma.ExamAnalyticsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExamAnalytics.
   */
  cursor?: Prisma.ExamAnalyticsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExamAnalytics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExamAnalytics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExamAnalytics.
   */
  distinct?: Prisma.ExamAnalyticsScalarFieldEnum | Prisma.ExamAnalyticsScalarFieldEnum[]
}

/**
 * ExamAnalytics findFirstOrThrow
 */
export type ExamAnalyticsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter, which ExamAnalytics to fetch.
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExamAnalytics to fetch.
   */
  orderBy?: Prisma.ExamAnalyticsOrderByWithRelationInput | Prisma.ExamAnalyticsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExamAnalytics.
   */
  cursor?: Prisma.ExamAnalyticsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExamAnalytics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExamAnalytics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExamAnalytics.
   */
  distinct?: Prisma.ExamAnalyticsScalarFieldEnum | Prisma.ExamAnalyticsScalarFieldEnum[]
}

/**
 * ExamAnalytics findMany
 */
export type ExamAnalyticsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter, which ExamAnalytics to fetch.
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExamAnalytics to fetch.
   */
  orderBy?: Prisma.ExamAnalyticsOrderByWithRelationInput | Prisma.ExamAnalyticsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExamAnalytics.
   */
  cursor?: Prisma.ExamAnalyticsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExamAnalytics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExamAnalytics.
   */
  skip?: number
  distinct?: Prisma.ExamAnalyticsScalarFieldEnum | Prisma.ExamAnalyticsScalarFieldEnum[]
}

/**
 * ExamAnalytics create
 */
export type ExamAnalyticsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * The data needed to create a ExamAnalytics.
   */
  data: Prisma.XOR<Prisma.ExamAnalyticsCreateInput, Prisma.ExamAnalyticsUncheckedCreateInput>
}

/**
 * ExamAnalytics createMany
 */
export type ExamAnalyticsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExamAnalytics.
   */
  data: Prisma.ExamAnalyticsCreateManyInput | Prisma.ExamAnalyticsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExamAnalytics createManyAndReturn
 */
export type ExamAnalyticsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * The data used to create many ExamAnalytics.
   */
  data: Prisma.ExamAnalyticsCreateManyInput | Prisma.ExamAnalyticsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExamAnalytics update
 */
export type ExamAnalyticsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * The data needed to update a ExamAnalytics.
   */
  data: Prisma.XOR<Prisma.ExamAnalyticsUpdateInput, Prisma.ExamAnalyticsUncheckedUpdateInput>
  /**
   * Choose, which ExamAnalytics to update.
   */
  where: Prisma.ExamAnalyticsWhereUniqueInput
}

/**
 * ExamAnalytics updateMany
 */
export type ExamAnalyticsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExamAnalytics.
   */
  data: Prisma.XOR<Prisma.ExamAnalyticsUpdateManyMutationInput, Prisma.ExamAnalyticsUncheckedUpdateManyInput>
  /**
   * Filter which ExamAnalytics to update
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * Limit how many ExamAnalytics to update.
   */
  limit?: number
}

/**
 * ExamAnalytics updateManyAndReturn
 */
export type ExamAnalyticsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * The data used to update ExamAnalytics.
   */
  data: Prisma.XOR<Prisma.ExamAnalyticsUpdateManyMutationInput, Prisma.ExamAnalyticsUncheckedUpdateManyInput>
  /**
   * Filter which ExamAnalytics to update
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * Limit how many ExamAnalytics to update.
   */
  limit?: number
}

/**
 * ExamAnalytics upsert
 */
export type ExamAnalyticsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * The filter to search for the ExamAnalytics to update in case it exists.
   */
  where: Prisma.ExamAnalyticsWhereUniqueInput
  /**
   * In case the ExamAnalytics found by the `where` argument doesn't exist, create a new ExamAnalytics with this data.
   */
  create: Prisma.XOR<Prisma.ExamAnalyticsCreateInput, Prisma.ExamAnalyticsUncheckedCreateInput>
  /**
   * In case the ExamAnalytics was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExamAnalyticsUpdateInput, Prisma.ExamAnalyticsUncheckedUpdateInput>
}

/**
 * ExamAnalytics delete
 */
export type ExamAnalyticsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
  /**
   * Filter which ExamAnalytics to delete.
   */
  where: Prisma.ExamAnalyticsWhereUniqueInput
}

/**
 * ExamAnalytics deleteMany
 */
export type ExamAnalyticsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExamAnalytics to delete
   */
  where?: Prisma.ExamAnalyticsWhereInput
  /**
   * Limit how many ExamAnalytics to delete.
   */
  limit?: number
}

/**
 * ExamAnalytics without action
 */
export type ExamAnalyticsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExamAnalytics
   */
  select?: Prisma.ExamAnalyticsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExamAnalytics
   */
  omit?: Prisma.ExamAnalyticsOmit<ExtArgs> | null
}
