
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AcademicTopic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AcademicTopic
 * 
 */
export type AcademicTopicModel = runtime.Types.Result.DefaultSelection<Prisma.$AcademicTopicPayload>

export type AggregateAcademicTopic = {
  _count: AcademicTopicCountAggregateOutputType | null
  _avg: AcademicTopicAvgAggregateOutputType | null
  _sum: AcademicTopicSumAggregateOutputType | null
  _min: AcademicTopicMinAggregateOutputType | null
  _max: AcademicTopicMaxAggregateOutputType | null
}

export type AcademicTopicAvgAggregateOutputType = {
  position: number | null
}

export type AcademicTopicSumAggregateOutputType = {
  position: number | null
}

export type AcademicTopicMinAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicTopicMaxAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicTopicCountAggregateOutputType = {
  id: number
  name: number
  displayName: number
  position: number
  isActive: number
  chapterId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AcademicTopicAvgAggregateInputType = {
  position?: true
}

export type AcademicTopicSumAggregateInputType = {
  position?: true
}

export type AcademicTopicMinAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicTopicMaxAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicTopicCountAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AcademicTopicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicTopic to aggregate.
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicTopics to fetch.
   */
  orderBy?: Prisma.AcademicTopicOrderByWithRelationInput | Prisma.AcademicTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AcademicTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AcademicTopics
  **/
  _count?: true | AcademicTopicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AcademicTopicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AcademicTopicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AcademicTopicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AcademicTopicMaxAggregateInputType
}

export type GetAcademicTopicAggregateType<T extends AcademicTopicAggregateArgs> = {
      [P in keyof T & keyof AggregateAcademicTopic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAcademicTopic[P]>
    : Prisma.GetScalarType<T[P], AggregateAcademicTopic[P]>
}




export type AcademicTopicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicTopicWhereInput
  orderBy?: Prisma.AcademicTopicOrderByWithAggregationInput | Prisma.AcademicTopicOrderByWithAggregationInput[]
  by: Prisma.AcademicTopicScalarFieldEnum[] | Prisma.AcademicTopicScalarFieldEnum
  having?: Prisma.AcademicTopicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AcademicTopicCountAggregateInputType | true
  _avg?: AcademicTopicAvgAggregateInputType
  _sum?: AcademicTopicSumAggregateInputType
  _min?: AcademicTopicMinAggregateInputType
  _max?: AcademicTopicMaxAggregateInputType
}

export type AcademicTopicGroupByOutputType = {
  id: string
  name: string
  displayName: string
  position: number
  isActive: boolean
  chapterId: string
  createdAt: Date
  updatedAt: Date
  _count: AcademicTopicCountAggregateOutputType | null
  _avg: AcademicTopicAvgAggregateOutputType | null
  _sum: AcademicTopicSumAggregateOutputType | null
  _min: AcademicTopicMinAggregateOutputType | null
  _max: AcademicTopicMaxAggregateOutputType | null
}

type GetAcademicTopicGroupByPayload<T extends AcademicTopicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AcademicTopicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AcademicTopicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AcademicTopicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AcademicTopicGroupByOutputType[P]>
      }
    >
  >



export type AcademicTopicWhereInput = {
  AND?: Prisma.AcademicTopicWhereInput | Prisma.AcademicTopicWhereInput[]
  OR?: Prisma.AcademicTopicWhereInput[]
  NOT?: Prisma.AcademicTopicWhereInput | Prisma.AcademicTopicWhereInput[]
  id?: Prisma.StringFilter<"AcademicTopic"> | string
  name?: Prisma.StringFilter<"AcademicTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicTopic"> | string
  position?: Prisma.IntFilter<"AcademicTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicTopic"> | boolean
  chapterId?: Prisma.StringFilter<"AcademicTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
  chapter?: Prisma.XOR<Prisma.AcademicChapterScalarRelationFilter, Prisma.AcademicChapterWhereInput>
  subtopics?: Prisma.AcademicSubTopicListRelationFilter
  mcqs?: Prisma.McqListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}

export type AcademicTopicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  chapter?: Prisma.AcademicChapterOrderByWithRelationInput
  subtopics?: Prisma.AcademicSubTopicOrderByRelationAggregateInput
  mcqs?: Prisma.McqOrderByRelationAggregateInput
  cqs?: Prisma.CqOrderByRelationAggregateInput
}

export type AcademicTopicWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AcademicTopicWhereInput | Prisma.AcademicTopicWhereInput[]
  OR?: Prisma.AcademicTopicWhereInput[]
  NOT?: Prisma.AcademicTopicWhereInput | Prisma.AcademicTopicWhereInput[]
  name?: Prisma.StringFilter<"AcademicTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicTopic"> | string
  position?: Prisma.IntFilter<"AcademicTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicTopic"> | boolean
  chapterId?: Prisma.StringFilter<"AcademicTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
  chapter?: Prisma.XOR<Prisma.AcademicChapterScalarRelationFilter, Prisma.AcademicChapterWhereInput>
  subtopics?: Prisma.AcademicSubTopicListRelationFilter
  mcqs?: Prisma.McqListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}, "id">

export type AcademicTopicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AcademicTopicCountOrderByAggregateInput
  _avg?: Prisma.AcademicTopicAvgOrderByAggregateInput
  _max?: Prisma.AcademicTopicMaxOrderByAggregateInput
  _min?: Prisma.AcademicTopicMinOrderByAggregateInput
  _sum?: Prisma.AcademicTopicSumOrderByAggregateInput
}

export type AcademicTopicScalarWhereWithAggregatesInput = {
  AND?: Prisma.AcademicTopicScalarWhereWithAggregatesInput | Prisma.AcademicTopicScalarWhereWithAggregatesInput[]
  OR?: Prisma.AcademicTopicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AcademicTopicScalarWhereWithAggregatesInput | Prisma.AcademicTopicScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AcademicTopic"> | string
  name?: Prisma.StringWithAggregatesFilter<"AcademicTopic"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"AcademicTopic"> | string
  position?: Prisma.IntWithAggregatesFilter<"AcademicTopic"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"AcademicTopic"> | boolean
  chapterId?: Prisma.StringWithAggregatesFilter<"AcademicTopic"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicTopic"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicTopic"> | Date | string
}

export type AcademicTopicCreateInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutTopicsInput
  subtopics?: Prisma.AcademicSubTopicCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUncheckedCreateInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  chapterId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutTopicsNestedInput
  subtopics?: Prisma.AcademicSubTopicUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicCreateManyInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  chapterId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicTopicUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicTopicUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicTopicListRelationFilter = {
  every?: Prisma.AcademicTopicWhereInput
  some?: Prisma.AcademicTopicWhereInput
  none?: Prisma.AcademicTopicWhereInput
}

export type AcademicTopicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AcademicTopicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicTopicAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicTopicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicTopicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicTopicSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicTopicScalarRelationFilter = {
  is?: Prisma.AcademicTopicWhereInput
  isNot?: Prisma.AcademicTopicWhereInput
}

export type AcademicTopicNullableScalarRelationFilter = {
  is?: Prisma.AcademicTopicWhereInput | null
  isNot?: Prisma.AcademicTopicWhereInput | null
}

export type AcademicTopicCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput> | Prisma.AcademicTopicCreateWithoutChapterInput[] | Prisma.AcademicTopicUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutChapterInput | Prisma.AcademicTopicCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.AcademicTopicCreateManyChapterInputEnvelope
  connect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
}

export type AcademicTopicUncheckedCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput> | Prisma.AcademicTopicCreateWithoutChapterInput[] | Prisma.AcademicTopicUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutChapterInput | Prisma.AcademicTopicCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.AcademicTopicCreateManyChapterInputEnvelope
  connect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
}

export type AcademicTopicUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput> | Prisma.AcademicTopicCreateWithoutChapterInput[] | Prisma.AcademicTopicUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutChapterInput | Prisma.AcademicTopicCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.AcademicTopicUpsertWithWhereUniqueWithoutChapterInput | Prisma.AcademicTopicUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.AcademicTopicCreateManyChapterInputEnvelope
  set?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  disconnect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  delete?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  connect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  update?: Prisma.AcademicTopicUpdateWithWhereUniqueWithoutChapterInput | Prisma.AcademicTopicUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.AcademicTopicUpdateManyWithWhereWithoutChapterInput | Prisma.AcademicTopicUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.AcademicTopicScalarWhereInput | Prisma.AcademicTopicScalarWhereInput[]
}

export type AcademicTopicUncheckedUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput> | Prisma.AcademicTopicCreateWithoutChapterInput[] | Prisma.AcademicTopicUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutChapterInput | Prisma.AcademicTopicCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.AcademicTopicUpsertWithWhereUniqueWithoutChapterInput | Prisma.AcademicTopicUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.AcademicTopicCreateManyChapterInputEnvelope
  set?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  disconnect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  delete?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  connect?: Prisma.AcademicTopicWhereUniqueInput | Prisma.AcademicTopicWhereUniqueInput[]
  update?: Prisma.AcademicTopicUpdateWithWhereUniqueWithoutChapterInput | Prisma.AcademicTopicUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.AcademicTopicUpdateManyWithWhereWithoutChapterInput | Prisma.AcademicTopicUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.AcademicTopicScalarWhereInput | Prisma.AcademicTopicScalarWhereInput[]
}

export type AcademicTopicCreateNestedOneWithoutSubtopicsInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedCreateWithoutSubtopicsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutSubtopicsInput
  connect?: Prisma.AcademicTopicWhereUniqueInput
}

export type AcademicTopicUpdateOneRequiredWithoutSubtopicsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedCreateWithoutSubtopicsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutSubtopicsInput
  upsert?: Prisma.AcademicTopicUpsertWithoutSubtopicsInput
  connect?: Prisma.AcademicTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicTopicUpdateToOneWithWhereWithoutSubtopicsInput, Prisma.AcademicTopicUpdateWithoutSubtopicsInput>, Prisma.AcademicTopicUncheckedUpdateWithoutSubtopicsInput>
}

export type AcademicTopicCreateNestedOneWithoutMcqsInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutMcqsInput, Prisma.AcademicTopicUncheckedCreateWithoutMcqsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutMcqsInput
  connect?: Prisma.AcademicTopicWhereUniqueInput
}

export type AcademicTopicUpdateOneWithoutMcqsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutMcqsInput, Prisma.AcademicTopicUncheckedCreateWithoutMcqsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutMcqsInput
  upsert?: Prisma.AcademicTopicUpsertWithoutMcqsInput
  disconnect?: Prisma.AcademicTopicWhereInput | boolean
  delete?: Prisma.AcademicTopicWhereInput | boolean
  connect?: Prisma.AcademicTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicTopicUpdateToOneWithWhereWithoutMcqsInput, Prisma.AcademicTopicUpdateWithoutMcqsInput>, Prisma.AcademicTopicUncheckedUpdateWithoutMcqsInput>
}

export type AcademicTopicCreateNestedOneWithoutCqsInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutCqsInput, Prisma.AcademicTopicUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutCqsInput
  connect?: Prisma.AcademicTopicWhereUniqueInput
}

export type AcademicTopicUpdateOneWithoutCqsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicTopicCreateWithoutCqsInput, Prisma.AcademicTopicUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicTopicCreateOrConnectWithoutCqsInput
  upsert?: Prisma.AcademicTopicUpsertWithoutCqsInput
  disconnect?: Prisma.AcademicTopicWhereInput | boolean
  delete?: Prisma.AcademicTopicWhereInput | boolean
  connect?: Prisma.AcademicTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicTopicUpdateToOneWithWhereWithoutCqsInput, Prisma.AcademicTopicUpdateWithoutCqsInput>, Prisma.AcademicTopicUncheckedUpdateWithoutCqsInput>
}

export type AcademicTopicCreateWithoutChapterInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subtopics?: Prisma.AcademicSubTopicCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUncheckedCreateWithoutChapterInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutTopicInput
}

export type AcademicTopicCreateOrConnectWithoutChapterInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput>
}

export type AcademicTopicCreateManyChapterInputEnvelope = {
  data: Prisma.AcademicTopicCreateManyChapterInput | Prisma.AcademicTopicCreateManyChapterInput[]
  skipDuplicates?: boolean
}

export type AcademicTopicUpsertWithWhereUniqueWithoutChapterInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  update: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutChapterInput, Prisma.AcademicTopicUncheckedUpdateWithoutChapterInput>
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutChapterInput, Prisma.AcademicTopicUncheckedCreateWithoutChapterInput>
}

export type AcademicTopicUpdateWithWhereUniqueWithoutChapterInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  data: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutChapterInput, Prisma.AcademicTopicUncheckedUpdateWithoutChapterInput>
}

export type AcademicTopicUpdateManyWithWhereWithoutChapterInput = {
  where: Prisma.AcademicTopicScalarWhereInput
  data: Prisma.XOR<Prisma.AcademicTopicUpdateManyMutationInput, Prisma.AcademicTopicUncheckedUpdateManyWithoutChapterInput>
}

export type AcademicTopicScalarWhereInput = {
  AND?: Prisma.AcademicTopicScalarWhereInput | Prisma.AcademicTopicScalarWhereInput[]
  OR?: Prisma.AcademicTopicScalarWhereInput[]
  NOT?: Prisma.AcademicTopicScalarWhereInput | Prisma.AcademicTopicScalarWhereInput[]
  id?: Prisma.StringFilter<"AcademicTopic"> | string
  name?: Prisma.StringFilter<"AcademicTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicTopic"> | string
  position?: Prisma.IntFilter<"AcademicTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicTopic"> | boolean
  chapterId?: Prisma.StringFilter<"AcademicTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicTopic"> | Date | string
}

export type AcademicTopicCreateWithoutSubtopicsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutTopicsInput
  mcqs?: Prisma.McqCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUncheckedCreateWithoutSubtopicsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  chapterId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutTopicInput
}

export type AcademicTopicCreateOrConnectWithoutSubtopicsInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedCreateWithoutSubtopicsInput>
}

export type AcademicTopicUpsertWithoutSubtopicsInput = {
  update: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedUpdateWithoutSubtopicsInput>
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedCreateWithoutSubtopicsInput>
  where?: Prisma.AcademicTopicWhereInput
}

export type AcademicTopicUpdateToOneWithWhereWithoutSubtopicsInput = {
  where?: Prisma.AcademicTopicWhereInput
  data: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutSubtopicsInput, Prisma.AcademicTopicUncheckedUpdateWithoutSubtopicsInput>
}

export type AcademicTopicUpdateWithoutSubtopicsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutTopicsNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateWithoutSubtopicsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicCreateWithoutMcqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutTopicsInput
  subtopics?: Prisma.AcademicSubTopicCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUncheckedCreateWithoutMcqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  chapterId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedCreateNestedManyWithoutTopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutTopicInput
}

export type AcademicTopicCreateOrConnectWithoutMcqsInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutMcqsInput, Prisma.AcademicTopicUncheckedCreateWithoutMcqsInput>
}

export type AcademicTopicUpsertWithoutMcqsInput = {
  update: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutMcqsInput, Prisma.AcademicTopicUncheckedUpdateWithoutMcqsInput>
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutMcqsInput, Prisma.AcademicTopicUncheckedCreateWithoutMcqsInput>
  where?: Prisma.AcademicTopicWhereInput
}

export type AcademicTopicUpdateToOneWithWhereWithoutMcqsInput = {
  where?: Prisma.AcademicTopicWhereInput
  data: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutMcqsInput, Prisma.AcademicTopicUncheckedUpdateWithoutMcqsInput>
}

export type AcademicTopicUpdateWithoutMcqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutTopicsNestedInput
  subtopics?: Prisma.AcademicSubTopicUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateWithoutMcqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicCreateWithoutCqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  chapter: Prisma.AcademicChapterCreateNestedOneWithoutTopicsInput
  subtopics?: Prisma.AcademicSubTopicCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqCreateNestedManyWithoutTopicInput
}

export type AcademicTopicUncheckedCreateWithoutCqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  chapterId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedCreateNestedManyWithoutTopicInput
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutTopicInput
}

export type AcademicTopicCreateOrConnectWithoutCqsInput = {
  where: Prisma.AcademicTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutCqsInput, Prisma.AcademicTopicUncheckedCreateWithoutCqsInput>
}

export type AcademicTopicUpsertWithoutCqsInput = {
  update: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutCqsInput, Prisma.AcademicTopicUncheckedUpdateWithoutCqsInput>
  create: Prisma.XOR<Prisma.AcademicTopicCreateWithoutCqsInput, Prisma.AcademicTopicUncheckedCreateWithoutCqsInput>
  where?: Prisma.AcademicTopicWhereInput
}

export type AcademicTopicUpdateToOneWithWhereWithoutCqsInput = {
  where?: Prisma.AcademicTopicWhereInput
  data: Prisma.XOR<Prisma.AcademicTopicUpdateWithoutCqsInput, Prisma.AcademicTopicUncheckedUpdateWithoutCqsInput>
}

export type AcademicTopicUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapter?: Prisma.AcademicChapterUpdateOneRequiredWithoutTopicsNestedInput
  subtopics?: Prisma.AcademicSubTopicUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicCreateManyChapterInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicTopicUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtopics?: Prisma.AcademicSubTopicUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subtopics?: Prisma.AcademicSubTopicUncheckedUpdateManyWithoutTopicNestedInput
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutTopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutTopicNestedInput
}

export type AcademicTopicUncheckedUpdateManyWithoutChapterInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AcademicTopicCountOutputType
 */

export type AcademicTopicCountOutputType = {
  subtopics: number
  mcqs: number
  cqs: number
}

export type AcademicTopicCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subtopics?: boolean | AcademicTopicCountOutputTypeCountSubtopicsArgs
  mcqs?: boolean | AcademicTopicCountOutputTypeCountMcqsArgs
  cqs?: boolean | AcademicTopicCountOutputTypeCountCqsArgs
}

/**
 * AcademicTopicCountOutputType without action
 */
export type AcademicTopicCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopicCountOutputType
   */
  select?: Prisma.AcademicTopicCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AcademicTopicCountOutputType without action
 */
export type AcademicTopicCountOutputTypeCountSubtopicsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSubTopicWhereInput
}

/**
 * AcademicTopicCountOutputType without action
 */
export type AcademicTopicCountOutputTypeCountMcqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McqWhereInput
}

/**
 * AcademicTopicCountOutputType without action
 */
export type AcademicTopicCountOutputTypeCountCqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CqWhereInput
}


export type AcademicTopicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  subtopics?: boolean | Prisma.AcademicTopic$subtopicsArgs<ExtArgs>
  mcqs?: boolean | Prisma.AcademicTopic$mcqsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicTopic$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicTopicCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicTopic"]>

export type AcademicTopicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicTopic"]>

export type AcademicTopicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicTopic"]>

export type AcademicTopicSelectScalar = {
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AcademicTopicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "displayName" | "position" | "isActive" | "chapterId" | "createdAt" | "updatedAt", ExtArgs["result"]["academicTopic"]>
export type AcademicTopicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
  subtopics?: boolean | Prisma.AcademicTopic$subtopicsArgs<ExtArgs>
  mcqs?: boolean | Prisma.AcademicTopic$mcqsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicTopic$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicTopicCountOutputTypeDefaultArgs<ExtArgs>
}
export type AcademicTopicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
}
export type AcademicTopicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.AcademicChapterDefaultArgs<ExtArgs>
}

export type $AcademicTopicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AcademicTopic"
  objects: {
    chapter: Prisma.$AcademicChapterPayload<ExtArgs>
    subtopics: Prisma.$AcademicSubTopicPayload<ExtArgs>[]
    mcqs: Prisma.$McqPayload<ExtArgs>[]
    cqs: Prisma.$CqPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    displayName: string
    position: number
    isActive: boolean
    chapterId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["academicTopic"]>
  composites: {}
}

export type AcademicTopicGetPayload<S extends boolean | null | undefined | AcademicTopicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload, S>

export type AcademicTopicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AcademicTopicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AcademicTopicCountAggregateInputType | true
  }

export interface AcademicTopicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AcademicTopic'], meta: { name: 'AcademicTopic' } }
  /**
   * Find zero or one AcademicTopic that matches the filter.
   * @param {AcademicTopicFindUniqueArgs} args - Arguments to find a AcademicTopic
   * @example
   * // Get one AcademicTopic
   * const academicTopic = await prisma.academicTopic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AcademicTopicFindUniqueArgs>(args: Prisma.SelectSubset<T, AcademicTopicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AcademicTopic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AcademicTopicFindUniqueOrThrowArgs} args - Arguments to find a AcademicTopic
   * @example
   * // Get one AcademicTopic
   * const academicTopic = await prisma.academicTopic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AcademicTopicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AcademicTopicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicTopic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicFindFirstArgs} args - Arguments to find a AcademicTopic
   * @example
   * // Get one AcademicTopic
   * const academicTopic = await prisma.academicTopic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AcademicTopicFindFirstArgs>(args?: Prisma.SelectSubset<T, AcademicTopicFindFirstArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicTopic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicFindFirstOrThrowArgs} args - Arguments to find a AcademicTopic
   * @example
   * // Get one AcademicTopic
   * const academicTopic = await prisma.academicTopic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AcademicTopicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AcademicTopicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AcademicTopics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AcademicTopics
   * const academicTopics = await prisma.academicTopic.findMany()
   * 
   * // Get first 10 AcademicTopics
   * const academicTopics = await prisma.academicTopic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const academicTopicWithIdOnly = await prisma.academicTopic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AcademicTopicFindManyArgs>(args?: Prisma.SelectSubset<T, AcademicTopicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AcademicTopic.
   * @param {AcademicTopicCreateArgs} args - Arguments to create a AcademicTopic.
   * @example
   * // Create one AcademicTopic
   * const AcademicTopic = await prisma.academicTopic.create({
   *   data: {
   *     // ... data to create a AcademicTopic
   *   }
   * })
   * 
   */
  create<T extends AcademicTopicCreateArgs>(args: Prisma.SelectSubset<T, AcademicTopicCreateArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AcademicTopics.
   * @param {AcademicTopicCreateManyArgs} args - Arguments to create many AcademicTopics.
   * @example
   * // Create many AcademicTopics
   * const academicTopic = await prisma.academicTopic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AcademicTopicCreateManyArgs>(args?: Prisma.SelectSubset<T, AcademicTopicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AcademicTopics and returns the data saved in the database.
   * @param {AcademicTopicCreateManyAndReturnArgs} args - Arguments to create many AcademicTopics.
   * @example
   * // Create many AcademicTopics
   * const academicTopic = await prisma.academicTopic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AcademicTopics and only return the `id`
   * const academicTopicWithIdOnly = await prisma.academicTopic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AcademicTopicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AcademicTopicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AcademicTopic.
   * @param {AcademicTopicDeleteArgs} args - Arguments to delete one AcademicTopic.
   * @example
   * // Delete one AcademicTopic
   * const AcademicTopic = await prisma.academicTopic.delete({
   *   where: {
   *     // ... filter to delete one AcademicTopic
   *   }
   * })
   * 
   */
  delete<T extends AcademicTopicDeleteArgs>(args: Prisma.SelectSubset<T, AcademicTopicDeleteArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AcademicTopic.
   * @param {AcademicTopicUpdateArgs} args - Arguments to update one AcademicTopic.
   * @example
   * // Update one AcademicTopic
   * const academicTopic = await prisma.academicTopic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AcademicTopicUpdateArgs>(args: Prisma.SelectSubset<T, AcademicTopicUpdateArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AcademicTopics.
   * @param {AcademicTopicDeleteManyArgs} args - Arguments to filter AcademicTopics to delete.
   * @example
   * // Delete a few AcademicTopics
   * const { count } = await prisma.academicTopic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AcademicTopicDeleteManyArgs>(args?: Prisma.SelectSubset<T, AcademicTopicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AcademicTopics
   * const academicTopic = await prisma.academicTopic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AcademicTopicUpdateManyArgs>(args: Prisma.SelectSubset<T, AcademicTopicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicTopics and returns the data updated in the database.
   * @param {AcademicTopicUpdateManyAndReturnArgs} args - Arguments to update many AcademicTopics.
   * @example
   * // Update many AcademicTopics
   * const academicTopic = await prisma.academicTopic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AcademicTopics and only return the `id`
   * const academicTopicWithIdOnly = await prisma.academicTopic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AcademicTopicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AcademicTopicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AcademicTopic.
   * @param {AcademicTopicUpsertArgs} args - Arguments to update or create a AcademicTopic.
   * @example
   * // Update or create a AcademicTopic
   * const academicTopic = await prisma.academicTopic.upsert({
   *   create: {
   *     // ... data to create a AcademicTopic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AcademicTopic we want to update
   *   }
   * })
   */
  upsert<T extends AcademicTopicUpsertArgs>(args: Prisma.SelectSubset<T, AcademicTopicUpsertArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AcademicTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicCountArgs} args - Arguments to filter AcademicTopics to count.
   * @example
   * // Count the number of AcademicTopics
   * const count = await prisma.academicTopic.count({
   *   where: {
   *     // ... the filter for the AcademicTopics we want to count
   *   }
   * })
  **/
  count<T extends AcademicTopicCountArgs>(
    args?: Prisma.Subset<T, AcademicTopicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AcademicTopicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AcademicTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AcademicTopicAggregateArgs>(args: Prisma.Subset<T, AcademicTopicAggregateArgs>): Prisma.PrismaPromise<GetAcademicTopicAggregateType<T>>

  /**
   * Group by AcademicTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicTopicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AcademicTopicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AcademicTopicGroupByArgs['orderBy'] }
      : { orderBy?: AcademicTopicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AcademicTopicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAcademicTopicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AcademicTopic model
 */
readonly fields: AcademicTopicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AcademicTopic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AcademicTopicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chapter<T extends Prisma.AcademicChapterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicChapterDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicChapterClient<runtime.Types.Result.GetResult<Prisma.$AcademicChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  subtopics<T extends Prisma.AcademicTopic$subtopicsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicTopic$subtopicsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  mcqs<T extends Prisma.AcademicTopic$mcqsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicTopic$mcqsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cqs<T extends Prisma.AcademicTopic$cqsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicTopic$cqsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AcademicTopic model
 */
export interface AcademicTopicFieldRefs {
  readonly id: Prisma.FieldRef<"AcademicTopic", 'String'>
  readonly name: Prisma.FieldRef<"AcademicTopic", 'String'>
  readonly displayName: Prisma.FieldRef<"AcademicTopic", 'String'>
  readonly position: Prisma.FieldRef<"AcademicTopic", 'Int'>
  readonly isActive: Prisma.FieldRef<"AcademicTopic", 'Boolean'>
  readonly chapterId: Prisma.FieldRef<"AcademicTopic", 'String'>
  readonly createdAt: Prisma.FieldRef<"AcademicTopic", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AcademicTopic", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AcademicTopic findUnique
 */
export type AcademicTopicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicTopic to fetch.
   */
  where: Prisma.AcademicTopicWhereUniqueInput
}

/**
 * AcademicTopic findUniqueOrThrow
 */
export type AcademicTopicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicTopic to fetch.
   */
  where: Prisma.AcademicTopicWhereUniqueInput
}

/**
 * AcademicTopic findFirst
 */
export type AcademicTopicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicTopic to fetch.
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicTopics to fetch.
   */
  orderBy?: Prisma.AcademicTopicOrderByWithRelationInput | Prisma.AcademicTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicTopics.
   */
  cursor?: Prisma.AcademicTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicTopics.
   */
  distinct?: Prisma.AcademicTopicScalarFieldEnum | Prisma.AcademicTopicScalarFieldEnum[]
}

/**
 * AcademicTopic findFirstOrThrow
 */
export type AcademicTopicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicTopic to fetch.
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicTopics to fetch.
   */
  orderBy?: Prisma.AcademicTopicOrderByWithRelationInput | Prisma.AcademicTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicTopics.
   */
  cursor?: Prisma.AcademicTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicTopics.
   */
  distinct?: Prisma.AcademicTopicScalarFieldEnum | Prisma.AcademicTopicScalarFieldEnum[]
}

/**
 * AcademicTopic findMany
 */
export type AcademicTopicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicTopics to fetch.
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicTopics to fetch.
   */
  orderBy?: Prisma.AcademicTopicOrderByWithRelationInput | Prisma.AcademicTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AcademicTopics.
   */
  cursor?: Prisma.AcademicTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicTopics.
   */
  skip?: number
  distinct?: Prisma.AcademicTopicScalarFieldEnum | Prisma.AcademicTopicScalarFieldEnum[]
}

/**
 * AcademicTopic create
 */
export type AcademicTopicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * The data needed to create a AcademicTopic.
   */
  data: Prisma.XOR<Prisma.AcademicTopicCreateInput, Prisma.AcademicTopicUncheckedCreateInput>
}

/**
 * AcademicTopic createMany
 */
export type AcademicTopicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AcademicTopics.
   */
  data: Prisma.AcademicTopicCreateManyInput | Prisma.AcademicTopicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicTopic createManyAndReturn
 */
export type AcademicTopicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * The data used to create many AcademicTopics.
   */
  data: Prisma.AcademicTopicCreateManyInput | Prisma.AcademicTopicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicTopic update
 */
export type AcademicTopicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * The data needed to update a AcademicTopic.
   */
  data: Prisma.XOR<Prisma.AcademicTopicUpdateInput, Prisma.AcademicTopicUncheckedUpdateInput>
  /**
   * Choose, which AcademicTopic to update.
   */
  where: Prisma.AcademicTopicWhereUniqueInput
}

/**
 * AcademicTopic updateMany
 */
export type AcademicTopicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AcademicTopics.
   */
  data: Prisma.XOR<Prisma.AcademicTopicUpdateManyMutationInput, Prisma.AcademicTopicUncheckedUpdateManyInput>
  /**
   * Filter which AcademicTopics to update
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * Limit how many AcademicTopics to update.
   */
  limit?: number
}

/**
 * AcademicTopic updateManyAndReturn
 */
export type AcademicTopicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * The data used to update AcademicTopics.
   */
  data: Prisma.XOR<Prisma.AcademicTopicUpdateManyMutationInput, Prisma.AcademicTopicUncheckedUpdateManyInput>
  /**
   * Filter which AcademicTopics to update
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * Limit how many AcademicTopics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicTopic upsert
 */
export type AcademicTopicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * The filter to search for the AcademicTopic to update in case it exists.
   */
  where: Prisma.AcademicTopicWhereUniqueInput
  /**
   * In case the AcademicTopic found by the `where` argument doesn't exist, create a new AcademicTopic with this data.
   */
  create: Prisma.XOR<Prisma.AcademicTopicCreateInput, Prisma.AcademicTopicUncheckedCreateInput>
  /**
   * In case the AcademicTopic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AcademicTopicUpdateInput, Prisma.AcademicTopicUncheckedUpdateInput>
}

/**
 * AcademicTopic delete
 */
export type AcademicTopicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
  /**
   * Filter which AcademicTopic to delete.
   */
  where: Prisma.AcademicTopicWhereUniqueInput
}

/**
 * AcademicTopic deleteMany
 */
export type AcademicTopicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicTopics to delete
   */
  where?: Prisma.AcademicTopicWhereInput
  /**
   * Limit how many AcademicTopics to delete.
   */
  limit?: number
}

/**
 * AcademicTopic.subtopics
 */
export type AcademicTopic$subtopicsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  where?: Prisma.AcademicSubTopicWhereInput
  orderBy?: Prisma.AcademicSubTopicOrderByWithRelationInput | Prisma.AcademicSubTopicOrderByWithRelationInput[]
  cursor?: Prisma.AcademicSubTopicWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicSubTopicScalarFieldEnum | Prisma.AcademicSubTopicScalarFieldEnum[]
}

/**
 * AcademicTopic.mcqs
 */
export type AcademicTopic$mcqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mcq
   */
  select?: Prisma.McqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mcq
   */
  omit?: Prisma.McqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McqInclude<ExtArgs> | null
  where?: Prisma.McqWhereInput
  orderBy?: Prisma.McqOrderByWithRelationInput | Prisma.McqOrderByWithRelationInput[]
  cursor?: Prisma.McqWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.McqScalarFieldEnum | Prisma.McqScalarFieldEnum[]
}

/**
 * AcademicTopic.cqs
 */
export type AcademicTopic$cqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  where?: Prisma.CqWhereInput
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  cursor?: Prisma.CqWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * AcademicTopic without action
 */
export type AcademicTopicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicTopic
   */
  select?: Prisma.AcademicTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicTopic
   */
  omit?: Prisma.AcademicTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicTopicInclude<ExtArgs> | null
}
