
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AcademicSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AcademicSession
 * 
 */
export type AcademicSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$AcademicSessionPayload>

export type AggregateAcademicSession = {
  _count: AcademicSessionCountAggregateOutputType | null
  _min: AcademicSessionMinAggregateOutputType | null
  _max: AcademicSessionMaxAggregateOutputType | null
}

export type AcademicSessionMinAggregateOutputType = {
  id: string | null
  academicYearId: string | null
  name: string | null
  startDate: Date | null
  endDate: Date | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicSessionMaxAggregateOutputType = {
  id: string | null
  academicYearId: string | null
  name: string | null
  startDate: Date | null
  endDate: Date | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicSessionCountAggregateOutputType = {
  id: number
  academicYearId: number
  name: number
  startDate: number
  endDate: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AcademicSessionMinAggregateInputType = {
  id?: true
  academicYearId?: true
  name?: true
  startDate?: true
  endDate?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicSessionMaxAggregateInputType = {
  id?: true
  academicYearId?: true
  name?: true
  startDate?: true
  endDate?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicSessionCountAggregateInputType = {
  id?: true
  academicYearId?: true
  name?: true
  startDate?: true
  endDate?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AcademicSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicSession to aggregate.
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSessions to fetch.
   */
  orderBy?: Prisma.AcademicSessionOrderByWithRelationInput | Prisma.AcademicSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AcademicSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AcademicSessions
  **/
  _count?: true | AcademicSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AcademicSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AcademicSessionMaxAggregateInputType
}

export type GetAcademicSessionAggregateType<T extends AcademicSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateAcademicSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAcademicSession[P]>
    : Prisma.GetScalarType<T[P], AggregateAcademicSession[P]>
}




export type AcademicSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSessionWhereInput
  orderBy?: Prisma.AcademicSessionOrderByWithAggregationInput | Prisma.AcademicSessionOrderByWithAggregationInput[]
  by: Prisma.AcademicSessionScalarFieldEnum[] | Prisma.AcademicSessionScalarFieldEnum
  having?: Prisma.AcademicSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AcademicSessionCountAggregateInputType | true
  _min?: AcademicSessionMinAggregateInputType
  _max?: AcademicSessionMaxAggregateInputType
}

export type AcademicSessionGroupByOutputType = {
  id: string
  academicYearId: string
  name: string
  startDate: Date
  endDate: Date
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: AcademicSessionCountAggregateOutputType | null
  _min: AcademicSessionMinAggregateOutputType | null
  _max: AcademicSessionMaxAggregateOutputType | null
}

type GetAcademicSessionGroupByPayload<T extends AcademicSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AcademicSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AcademicSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AcademicSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AcademicSessionGroupByOutputType[P]>
      }
    >
  >



export type AcademicSessionWhereInput = {
  AND?: Prisma.AcademicSessionWhereInput | Prisma.AcademicSessionWhereInput[]
  OR?: Prisma.AcademicSessionWhereInput[]
  NOT?: Prisma.AcademicSessionWhereInput | Prisma.AcademicSessionWhereInput[]
  id?: Prisma.StringFilter<"AcademicSession"> | string
  academicYearId?: Prisma.StringFilter<"AcademicSession"> | string
  name?: Prisma.StringFilter<"AcademicSession"> | string
  startDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  endDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  isActive?: Prisma.BoolFilter<"AcademicSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
  classes?: Prisma.AcademicSessionClassListRelationFilter
}

export type AcademicSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  academicYear?: Prisma.AcademicYearOrderByWithRelationInput
  classes?: Prisma.AcademicSessionClassOrderByRelationAggregateInput
}

export type AcademicSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AcademicSessionWhereInput | Prisma.AcademicSessionWhereInput[]
  OR?: Prisma.AcademicSessionWhereInput[]
  NOT?: Prisma.AcademicSessionWhereInput | Prisma.AcademicSessionWhereInput[]
  academicYearId?: Prisma.StringFilter<"AcademicSession"> | string
  name?: Prisma.StringFilter<"AcademicSession"> | string
  startDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  endDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  isActive?: Prisma.BoolFilter<"AcademicSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  academicYear?: Prisma.XOR<Prisma.AcademicYearScalarRelationFilter, Prisma.AcademicYearWhereInput>
  classes?: Prisma.AcademicSessionClassListRelationFilter
}, "id">

export type AcademicSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AcademicSessionCountOrderByAggregateInput
  _max?: Prisma.AcademicSessionMaxOrderByAggregateInput
  _min?: Prisma.AcademicSessionMinOrderByAggregateInput
}

export type AcademicSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.AcademicSessionScalarWhereWithAggregatesInput | Prisma.AcademicSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.AcademicSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AcademicSessionScalarWhereWithAggregatesInput | Prisma.AcademicSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AcademicSession"> | string
  academicYearId?: Prisma.StringWithAggregatesFilter<"AcademicSession"> | string
  name?: Prisma.StringWithAggregatesFilter<"AcademicSession"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"AcademicSession"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"AcademicSession"> | Date | string
  isActive?: Prisma.BoolWithAggregatesFilter<"AcademicSession"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicSession"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicSession"> | Date | string
}

export type AcademicSessionCreateInput = {
  id?: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutSessionsInput
  classes?: Prisma.AcademicSessionClassCreateNestedManyWithoutSessionInput
}

export type AcademicSessionUncheckedCreateInput = {
  id?: string
  academicYearId: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  classes?: Prisma.AcademicSessionClassUncheckedCreateNestedManyWithoutSessionInput
}

export type AcademicSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutSessionsNestedInput
  classes?: Prisma.AcademicSessionClassUpdateManyWithoutSessionNestedInput
}

export type AcademicSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  classes?: Prisma.AcademicSessionClassUncheckedUpdateManyWithoutSessionNestedInput
}

export type AcademicSessionCreateManyInput = {
  id?: string
  academicYearId: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicSessionListRelationFilter = {
  every?: Prisma.AcademicSessionWhereInput
  some?: Prisma.AcademicSessionWhereInput
  none?: Prisma.AcademicSessionWhereInput
}

export type AcademicSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AcademicSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  academicYearId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSessionScalarRelationFilter = {
  is?: Prisma.AcademicSessionWhereInput
  isNot?: Prisma.AcademicSessionWhereInput
}

export type AcademicSessionCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput> | Prisma.AcademicSessionCreateWithoutAcademicYearInput[] | Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput | Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.AcademicSessionCreateManyAcademicYearInputEnvelope
  connect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
}

export type AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput> | Prisma.AcademicSessionCreateWithoutAcademicYearInput[] | Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput | Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput[]
  createMany?: Prisma.AcademicSessionCreateManyAcademicYearInputEnvelope
  connect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
}

export type AcademicSessionUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput> | Prisma.AcademicSessionCreateWithoutAcademicYearInput[] | Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput | Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.AcademicSessionUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.AcademicSessionUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.AcademicSessionCreateManyAcademicYearInputEnvelope
  set?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  disconnect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  delete?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  connect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  update?: Prisma.AcademicSessionUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.AcademicSessionUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.AcademicSessionUpdateManyWithWhereWithoutAcademicYearInput | Prisma.AcademicSessionUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.AcademicSessionScalarWhereInput | Prisma.AcademicSessionScalarWhereInput[]
}

export type AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput> | Prisma.AcademicSessionCreateWithoutAcademicYearInput[] | Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput[]
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput | Prisma.AcademicSessionCreateOrConnectWithoutAcademicYearInput[]
  upsert?: Prisma.AcademicSessionUpsertWithWhereUniqueWithoutAcademicYearInput | Prisma.AcademicSessionUpsertWithWhereUniqueWithoutAcademicYearInput[]
  createMany?: Prisma.AcademicSessionCreateManyAcademicYearInputEnvelope
  set?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  disconnect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  delete?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  connect?: Prisma.AcademicSessionWhereUniqueInput | Prisma.AcademicSessionWhereUniqueInput[]
  update?: Prisma.AcademicSessionUpdateWithWhereUniqueWithoutAcademicYearInput | Prisma.AcademicSessionUpdateWithWhereUniqueWithoutAcademicYearInput[]
  updateMany?: Prisma.AcademicSessionUpdateManyWithWhereWithoutAcademicYearInput | Prisma.AcademicSessionUpdateManyWithWhereWithoutAcademicYearInput[]
  deleteMany?: Prisma.AcademicSessionScalarWhereInput | Prisma.AcademicSessionScalarWhereInput[]
}

export type AcademicSessionCreateNestedOneWithoutClassesInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutClassesInput, Prisma.AcademicSessionUncheckedCreateWithoutClassesInput>
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutClassesInput
  connect?: Prisma.AcademicSessionWhereUniqueInput
}

export type AcademicSessionUpdateOneRequiredWithoutClassesNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSessionCreateWithoutClassesInput, Prisma.AcademicSessionUncheckedCreateWithoutClassesInput>
  connectOrCreate?: Prisma.AcademicSessionCreateOrConnectWithoutClassesInput
  upsert?: Prisma.AcademicSessionUpsertWithoutClassesInput
  connect?: Prisma.AcademicSessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicSessionUpdateToOneWithWhereWithoutClassesInput, Prisma.AcademicSessionUpdateWithoutClassesInput>, Prisma.AcademicSessionUncheckedUpdateWithoutClassesInput>
}

export type AcademicSessionCreateWithoutAcademicYearInput = {
  id?: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  classes?: Prisma.AcademicSessionClassCreateNestedManyWithoutSessionInput
}

export type AcademicSessionUncheckedCreateWithoutAcademicYearInput = {
  id?: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  classes?: Prisma.AcademicSessionClassUncheckedCreateNestedManyWithoutSessionInput
}

export type AcademicSessionCreateOrConnectWithoutAcademicYearInput = {
  where: Prisma.AcademicSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput>
}

export type AcademicSessionCreateManyAcademicYearInputEnvelope = {
  data: Prisma.AcademicSessionCreateManyAcademicYearInput | Prisma.AcademicSessionCreateManyAcademicYearInput[]
  skipDuplicates?: boolean
}

export type AcademicSessionUpsertWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.AcademicSessionWhereUniqueInput
  update: Prisma.XOR<Prisma.AcademicSessionUpdateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedUpdateWithoutAcademicYearInput>
  create: Prisma.XOR<Prisma.AcademicSessionCreateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedCreateWithoutAcademicYearInput>
}

export type AcademicSessionUpdateWithWhereUniqueWithoutAcademicYearInput = {
  where: Prisma.AcademicSessionWhereUniqueInput
  data: Prisma.XOR<Prisma.AcademicSessionUpdateWithoutAcademicYearInput, Prisma.AcademicSessionUncheckedUpdateWithoutAcademicYearInput>
}

export type AcademicSessionUpdateManyWithWhereWithoutAcademicYearInput = {
  where: Prisma.AcademicSessionScalarWhereInput
  data: Prisma.XOR<Prisma.AcademicSessionUpdateManyMutationInput, Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearInput>
}

export type AcademicSessionScalarWhereInput = {
  AND?: Prisma.AcademicSessionScalarWhereInput | Prisma.AcademicSessionScalarWhereInput[]
  OR?: Prisma.AcademicSessionScalarWhereInput[]
  NOT?: Prisma.AcademicSessionScalarWhereInput | Prisma.AcademicSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"AcademicSession"> | string
  academicYearId?: Prisma.StringFilter<"AcademicSession"> | string
  name?: Prisma.StringFilter<"AcademicSession"> | string
  startDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  endDate?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  isActive?: Prisma.BoolFilter<"AcademicSession"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSession"> | Date | string
}

export type AcademicSessionCreateWithoutClassesInput = {
  id?: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  academicYear: Prisma.AcademicYearCreateNestedOneWithoutSessionsInput
}

export type AcademicSessionUncheckedCreateWithoutClassesInput = {
  id?: string
  academicYearId: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicSessionCreateOrConnectWithoutClassesInput = {
  where: Prisma.AcademicSessionWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicSessionCreateWithoutClassesInput, Prisma.AcademicSessionUncheckedCreateWithoutClassesInput>
}

export type AcademicSessionUpsertWithoutClassesInput = {
  update: Prisma.XOR<Prisma.AcademicSessionUpdateWithoutClassesInput, Prisma.AcademicSessionUncheckedUpdateWithoutClassesInput>
  create: Prisma.XOR<Prisma.AcademicSessionCreateWithoutClassesInput, Prisma.AcademicSessionUncheckedCreateWithoutClassesInput>
  where?: Prisma.AcademicSessionWhereInput
}

export type AcademicSessionUpdateToOneWithWhereWithoutClassesInput = {
  where?: Prisma.AcademicSessionWhereInput
  data: Prisma.XOR<Prisma.AcademicSessionUpdateWithoutClassesInput, Prisma.AcademicSessionUncheckedUpdateWithoutClassesInput>
}

export type AcademicSessionUpdateWithoutClassesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  academicYear?: Prisma.AcademicYearUpdateOneRequiredWithoutSessionsNestedInput
}

export type AcademicSessionUncheckedUpdateWithoutClassesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  academicYearId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicSessionCreateManyAcademicYearInput = {
  id?: string
  name: string
  startDate: Date | string
  endDate: Date | string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicSessionUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  classes?: Prisma.AcademicSessionClassUpdateManyWithoutSessionNestedInput
}

export type AcademicSessionUncheckedUpdateWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  classes?: Prisma.AcademicSessionClassUncheckedUpdateManyWithoutSessionNestedInput
}

export type AcademicSessionUncheckedUpdateManyWithoutAcademicYearInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AcademicSessionCountOutputType
 */

export type AcademicSessionCountOutputType = {
  classes: number
}

export type AcademicSessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  classes?: boolean | AcademicSessionCountOutputTypeCountClassesArgs
}

/**
 * AcademicSessionCountOutputType without action
 */
export type AcademicSessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSessionCountOutputType
   */
  select?: Prisma.AcademicSessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AcademicSessionCountOutputType without action
 */
export type AcademicSessionCountOutputTypeCountClassesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSessionClassWhereInput
}


export type AcademicSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  name?: boolean
  startDate?: boolean
  endDate?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  classes?: boolean | Prisma.AcademicSession$classesArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicSessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSession"]>

export type AcademicSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  name?: boolean
  startDate?: boolean
  endDate?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSession"]>

export type AcademicSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  academicYearId?: boolean
  name?: boolean
  startDate?: boolean
  endDate?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSession"]>

export type AcademicSessionSelectScalar = {
  id?: boolean
  academicYearId?: boolean
  name?: boolean
  startDate?: boolean
  endDate?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AcademicSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "academicYearId" | "name" | "startDate" | "endDate" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["academicSession"]>
export type AcademicSessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
  classes?: boolean | Prisma.AcademicSession$classesArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicSessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type AcademicSessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}
export type AcademicSessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  academicYear?: boolean | Prisma.AcademicYearDefaultArgs<ExtArgs>
}

export type $AcademicSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AcademicSession"
  objects: {
    academicYear: Prisma.$AcademicYearPayload<ExtArgs>
    classes: Prisma.$AcademicSessionClassPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    academicYearId: string
    name: string
    startDate: Date
    endDate: Date
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["academicSession"]>
  composites: {}
}

export type AcademicSessionGetPayload<S extends boolean | null | undefined | AcademicSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload, S>

export type AcademicSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AcademicSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AcademicSessionCountAggregateInputType | true
  }

export interface AcademicSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AcademicSession'], meta: { name: 'AcademicSession' } }
  /**
   * Find zero or one AcademicSession that matches the filter.
   * @param {AcademicSessionFindUniqueArgs} args - Arguments to find a AcademicSession
   * @example
   * // Get one AcademicSession
   * const academicSession = await prisma.academicSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AcademicSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, AcademicSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AcademicSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AcademicSessionFindUniqueOrThrowArgs} args - Arguments to find a AcademicSession
   * @example
   * // Get one AcademicSession
   * const academicSession = await prisma.academicSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AcademicSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AcademicSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionFindFirstArgs} args - Arguments to find a AcademicSession
   * @example
   * // Get one AcademicSession
   * const academicSession = await prisma.academicSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AcademicSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, AcademicSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionFindFirstOrThrowArgs} args - Arguments to find a AcademicSession
   * @example
   * // Get one AcademicSession
   * const academicSession = await prisma.academicSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AcademicSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AcademicSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AcademicSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AcademicSessions
   * const academicSessions = await prisma.academicSession.findMany()
   * 
   * // Get first 10 AcademicSessions
   * const academicSessions = await prisma.academicSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const academicSessionWithIdOnly = await prisma.academicSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AcademicSessionFindManyArgs>(args?: Prisma.SelectSubset<T, AcademicSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AcademicSession.
   * @param {AcademicSessionCreateArgs} args - Arguments to create a AcademicSession.
   * @example
   * // Create one AcademicSession
   * const AcademicSession = await prisma.academicSession.create({
   *   data: {
   *     // ... data to create a AcademicSession
   *   }
   * })
   * 
   */
  create<T extends AcademicSessionCreateArgs>(args: Prisma.SelectSubset<T, AcademicSessionCreateArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AcademicSessions.
   * @param {AcademicSessionCreateManyArgs} args - Arguments to create many AcademicSessions.
   * @example
   * // Create many AcademicSessions
   * const academicSession = await prisma.academicSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AcademicSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, AcademicSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AcademicSessions and returns the data saved in the database.
   * @param {AcademicSessionCreateManyAndReturnArgs} args - Arguments to create many AcademicSessions.
   * @example
   * // Create many AcademicSessions
   * const academicSession = await prisma.academicSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AcademicSessions and only return the `id`
   * const academicSessionWithIdOnly = await prisma.academicSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AcademicSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AcademicSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AcademicSession.
   * @param {AcademicSessionDeleteArgs} args - Arguments to delete one AcademicSession.
   * @example
   * // Delete one AcademicSession
   * const AcademicSession = await prisma.academicSession.delete({
   *   where: {
   *     // ... filter to delete one AcademicSession
   *   }
   * })
   * 
   */
  delete<T extends AcademicSessionDeleteArgs>(args: Prisma.SelectSubset<T, AcademicSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AcademicSession.
   * @param {AcademicSessionUpdateArgs} args - Arguments to update one AcademicSession.
   * @example
   * // Update one AcademicSession
   * const academicSession = await prisma.academicSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AcademicSessionUpdateArgs>(args: Prisma.SelectSubset<T, AcademicSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AcademicSessions.
   * @param {AcademicSessionDeleteManyArgs} args - Arguments to filter AcademicSessions to delete.
   * @example
   * // Delete a few AcademicSessions
   * const { count } = await prisma.academicSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AcademicSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, AcademicSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AcademicSessions
   * const academicSession = await prisma.academicSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AcademicSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, AcademicSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicSessions and returns the data updated in the database.
   * @param {AcademicSessionUpdateManyAndReturnArgs} args - Arguments to update many AcademicSessions.
   * @example
   * // Update many AcademicSessions
   * const academicSession = await prisma.academicSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AcademicSessions and only return the `id`
   * const academicSessionWithIdOnly = await prisma.academicSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AcademicSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AcademicSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AcademicSession.
   * @param {AcademicSessionUpsertArgs} args - Arguments to update or create a AcademicSession.
   * @example
   * // Update or create a AcademicSession
   * const academicSession = await prisma.academicSession.upsert({
   *   create: {
   *     // ... data to create a AcademicSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AcademicSession we want to update
   *   }
   * })
   */
  upsert<T extends AcademicSessionUpsertArgs>(args: Prisma.SelectSubset<T, AcademicSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__AcademicSessionClient<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AcademicSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionCountArgs} args - Arguments to filter AcademicSessions to count.
   * @example
   * // Count the number of AcademicSessions
   * const count = await prisma.academicSession.count({
   *   where: {
   *     // ... the filter for the AcademicSessions we want to count
   *   }
   * })
  **/
  count<T extends AcademicSessionCountArgs>(
    args?: Prisma.Subset<T, AcademicSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AcademicSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AcademicSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AcademicSessionAggregateArgs>(args: Prisma.Subset<T, AcademicSessionAggregateArgs>): Prisma.PrismaPromise<GetAcademicSessionAggregateType<T>>

  /**
   * Group by AcademicSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AcademicSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AcademicSessionGroupByArgs['orderBy'] }
      : { orderBy?: AcademicSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AcademicSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAcademicSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AcademicSession model
 */
readonly fields: AcademicSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AcademicSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AcademicSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  academicYear<T extends Prisma.AcademicYearDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYearDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  classes<T extends Prisma.AcademicSession$classesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicSession$classesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSessionClassPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AcademicSession model
 */
export interface AcademicSessionFieldRefs {
  readonly id: Prisma.FieldRef<"AcademicSession", 'String'>
  readonly academicYearId: Prisma.FieldRef<"AcademicSession", 'String'>
  readonly name: Prisma.FieldRef<"AcademicSession", 'String'>
  readonly startDate: Prisma.FieldRef<"AcademicSession", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"AcademicSession", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"AcademicSession", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AcademicSession", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AcademicSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AcademicSession findUnique
 */
export type AcademicSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSession to fetch.
   */
  where: Prisma.AcademicSessionWhereUniqueInput
}

/**
 * AcademicSession findUniqueOrThrow
 */
export type AcademicSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSession to fetch.
   */
  where: Prisma.AcademicSessionWhereUniqueInput
}

/**
 * AcademicSession findFirst
 */
export type AcademicSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSession to fetch.
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSessions to fetch.
   */
  orderBy?: Prisma.AcademicSessionOrderByWithRelationInput | Prisma.AcademicSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicSessions.
   */
  cursor?: Prisma.AcademicSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicSessions.
   */
  distinct?: Prisma.AcademicSessionScalarFieldEnum | Prisma.AcademicSessionScalarFieldEnum[]
}

/**
 * AcademicSession findFirstOrThrow
 */
export type AcademicSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSession to fetch.
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSessions to fetch.
   */
  orderBy?: Prisma.AcademicSessionOrderByWithRelationInput | Prisma.AcademicSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicSessions.
   */
  cursor?: Prisma.AcademicSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicSessions.
   */
  distinct?: Prisma.AcademicSessionScalarFieldEnum | Prisma.AcademicSessionScalarFieldEnum[]
}

/**
 * AcademicSession findMany
 */
export type AcademicSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSessions to fetch.
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSessions to fetch.
   */
  orderBy?: Prisma.AcademicSessionOrderByWithRelationInput | Prisma.AcademicSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AcademicSessions.
   */
  cursor?: Prisma.AcademicSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSessions.
   */
  skip?: number
  distinct?: Prisma.AcademicSessionScalarFieldEnum | Prisma.AcademicSessionScalarFieldEnum[]
}

/**
 * AcademicSession create
 */
export type AcademicSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a AcademicSession.
   */
  data: Prisma.XOR<Prisma.AcademicSessionCreateInput, Prisma.AcademicSessionUncheckedCreateInput>
}

/**
 * AcademicSession createMany
 */
export type AcademicSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AcademicSessions.
   */
  data: Prisma.AcademicSessionCreateManyInput | Prisma.AcademicSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicSession createManyAndReturn
 */
export type AcademicSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * The data used to create many AcademicSessions.
   */
  data: Prisma.AcademicSessionCreateManyInput | Prisma.AcademicSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicSession update
 */
export type AcademicSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a AcademicSession.
   */
  data: Prisma.XOR<Prisma.AcademicSessionUpdateInput, Prisma.AcademicSessionUncheckedUpdateInput>
  /**
   * Choose, which AcademicSession to update.
   */
  where: Prisma.AcademicSessionWhereUniqueInput
}

/**
 * AcademicSession updateMany
 */
export type AcademicSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AcademicSessions.
   */
  data: Prisma.XOR<Prisma.AcademicSessionUpdateManyMutationInput, Prisma.AcademicSessionUncheckedUpdateManyInput>
  /**
   * Filter which AcademicSessions to update
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * Limit how many AcademicSessions to update.
   */
  limit?: number
}

/**
 * AcademicSession updateManyAndReturn
 */
export type AcademicSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * The data used to update AcademicSessions.
   */
  data: Prisma.XOR<Prisma.AcademicSessionUpdateManyMutationInput, Prisma.AcademicSessionUncheckedUpdateManyInput>
  /**
   * Filter which AcademicSessions to update
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * Limit how many AcademicSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicSession upsert
 */
export type AcademicSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the AcademicSession to update in case it exists.
   */
  where: Prisma.AcademicSessionWhereUniqueInput
  /**
   * In case the AcademicSession found by the `where` argument doesn't exist, create a new AcademicSession with this data.
   */
  create: Prisma.XOR<Prisma.AcademicSessionCreateInput, Prisma.AcademicSessionUncheckedCreateInput>
  /**
   * In case the AcademicSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AcademicSessionUpdateInput, Prisma.AcademicSessionUncheckedUpdateInput>
}

/**
 * AcademicSession delete
 */
export type AcademicSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  /**
   * Filter which AcademicSession to delete.
   */
  where: Prisma.AcademicSessionWhereUniqueInput
}

/**
 * AcademicSession deleteMany
 */
export type AcademicSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicSessions to delete
   */
  where?: Prisma.AcademicSessionWhereInput
  /**
   * Limit how many AcademicSessions to delete.
   */
  limit?: number
}

/**
 * AcademicSession.classes
 */
export type AcademicSession$classesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSessionClass
   */
  select?: Prisma.AcademicSessionClassSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSessionClass
   */
  omit?: Prisma.AcademicSessionClassOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionClassInclude<ExtArgs> | null
  where?: Prisma.AcademicSessionClassWhereInput
  orderBy?: Prisma.AcademicSessionClassOrderByWithRelationInput | Prisma.AcademicSessionClassOrderByWithRelationInput[]
  cursor?: Prisma.AcademicSessionClassWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicSessionClassScalarFieldEnum | Prisma.AcademicSessionClassScalarFieldEnum[]
}

/**
 * AcademicSession without action
 */
export type AcademicSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
}
