
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AcademicSubTopic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AcademicSubTopic
 * 
 */
export type AcademicSubTopicModel = runtime.Types.Result.DefaultSelection<Prisma.$AcademicSubTopicPayload>

export type AggregateAcademicSubTopic = {
  _count: AcademicSubTopicCountAggregateOutputType | null
  _avg: AcademicSubTopicAvgAggregateOutputType | null
  _sum: AcademicSubTopicSumAggregateOutputType | null
  _min: AcademicSubTopicMinAggregateOutputType | null
  _max: AcademicSubTopicMaxAggregateOutputType | null
}

export type AcademicSubTopicAvgAggregateOutputType = {
  position: number | null
}

export type AcademicSubTopicSumAggregateOutputType = {
  position: number | null
}

export type AcademicSubTopicMinAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  topicId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicSubTopicMaxAggregateOutputType = {
  id: string | null
  name: string | null
  displayName: string | null
  position: number | null
  isActive: boolean | null
  topicId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicSubTopicCountAggregateOutputType = {
  id: number
  name: number
  displayName: number
  position: number
  isActive: number
  topicId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AcademicSubTopicAvgAggregateInputType = {
  position?: true
}

export type AcademicSubTopicSumAggregateInputType = {
  position?: true
}

export type AcademicSubTopicMinAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  topicId?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicSubTopicMaxAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  topicId?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicSubTopicCountAggregateInputType = {
  id?: true
  name?: true
  displayName?: true
  position?: true
  isActive?: true
  topicId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AcademicSubTopicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicSubTopic to aggregate.
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSubTopics to fetch.
   */
  orderBy?: Prisma.AcademicSubTopicOrderByWithRelationInput | Prisma.AcademicSubTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AcademicSubTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSubTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSubTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AcademicSubTopics
  **/
  _count?: true | AcademicSubTopicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AcademicSubTopicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AcademicSubTopicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AcademicSubTopicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AcademicSubTopicMaxAggregateInputType
}

export type GetAcademicSubTopicAggregateType<T extends AcademicSubTopicAggregateArgs> = {
      [P in keyof T & keyof AggregateAcademicSubTopic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAcademicSubTopic[P]>
    : Prisma.GetScalarType<T[P], AggregateAcademicSubTopic[P]>
}




export type AcademicSubTopicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSubTopicWhereInput
  orderBy?: Prisma.AcademicSubTopicOrderByWithAggregationInput | Prisma.AcademicSubTopicOrderByWithAggregationInput[]
  by: Prisma.AcademicSubTopicScalarFieldEnum[] | Prisma.AcademicSubTopicScalarFieldEnum
  having?: Prisma.AcademicSubTopicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AcademicSubTopicCountAggregateInputType | true
  _avg?: AcademicSubTopicAvgAggregateInputType
  _sum?: AcademicSubTopicSumAggregateInputType
  _min?: AcademicSubTopicMinAggregateInputType
  _max?: AcademicSubTopicMaxAggregateInputType
}

export type AcademicSubTopicGroupByOutputType = {
  id: string
  name: string
  displayName: string
  position: number
  isActive: boolean
  topicId: string
  createdAt: Date
  updatedAt: Date
  _count: AcademicSubTopicCountAggregateOutputType | null
  _avg: AcademicSubTopicAvgAggregateOutputType | null
  _sum: AcademicSubTopicSumAggregateOutputType | null
  _min: AcademicSubTopicMinAggregateOutputType | null
  _max: AcademicSubTopicMaxAggregateOutputType | null
}

type GetAcademicSubTopicGroupByPayload<T extends AcademicSubTopicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AcademicSubTopicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AcademicSubTopicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AcademicSubTopicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AcademicSubTopicGroupByOutputType[P]>
      }
    >
  >



export type AcademicSubTopicWhereInput = {
  AND?: Prisma.AcademicSubTopicWhereInput | Prisma.AcademicSubTopicWhereInput[]
  OR?: Prisma.AcademicSubTopicWhereInput[]
  NOT?: Prisma.AcademicSubTopicWhereInput | Prisma.AcademicSubTopicWhereInput[]
  id?: Prisma.StringFilter<"AcademicSubTopic"> | string
  name?: Prisma.StringFilter<"AcademicSubTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicSubTopic"> | string
  position?: Prisma.IntFilter<"AcademicSubTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicSubTopic"> | boolean
  topicId?: Prisma.StringFilter<"AcademicSubTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
  topic?: Prisma.XOR<Prisma.AcademicTopicScalarRelationFilter, Prisma.AcademicTopicWhereInput>
  mcqs?: Prisma.McqListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}

export type AcademicSubTopicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  topic?: Prisma.AcademicTopicOrderByWithRelationInput
  mcqs?: Prisma.McqOrderByRelationAggregateInput
  cqs?: Prisma.CqOrderByRelationAggregateInput
}

export type AcademicSubTopicWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AcademicSubTopicWhereInput | Prisma.AcademicSubTopicWhereInput[]
  OR?: Prisma.AcademicSubTopicWhereInput[]
  NOT?: Prisma.AcademicSubTopicWhereInput | Prisma.AcademicSubTopicWhereInput[]
  name?: Prisma.StringFilter<"AcademicSubTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicSubTopic"> | string
  position?: Prisma.IntFilter<"AcademicSubTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicSubTopic"> | boolean
  topicId?: Prisma.StringFilter<"AcademicSubTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
  topic?: Prisma.XOR<Prisma.AcademicTopicScalarRelationFilter, Prisma.AcademicTopicWhereInput>
  mcqs?: Prisma.McqListRelationFilter
  cqs?: Prisma.CqListRelationFilter
}, "id">

export type AcademicSubTopicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AcademicSubTopicCountOrderByAggregateInput
  _avg?: Prisma.AcademicSubTopicAvgOrderByAggregateInput
  _max?: Prisma.AcademicSubTopicMaxOrderByAggregateInput
  _min?: Prisma.AcademicSubTopicMinOrderByAggregateInput
  _sum?: Prisma.AcademicSubTopicSumOrderByAggregateInput
}

export type AcademicSubTopicScalarWhereWithAggregatesInput = {
  AND?: Prisma.AcademicSubTopicScalarWhereWithAggregatesInput | Prisma.AcademicSubTopicScalarWhereWithAggregatesInput[]
  OR?: Prisma.AcademicSubTopicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AcademicSubTopicScalarWhereWithAggregatesInput | Prisma.AcademicSubTopicScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AcademicSubTopic"> | string
  name?: Prisma.StringWithAggregatesFilter<"AcademicSubTopic"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"AcademicSubTopic"> | string
  position?: Prisma.IntWithAggregatesFilter<"AcademicSubTopic"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"AcademicSubTopic"> | boolean
  topicId?: Prisma.StringWithAggregatesFilter<"AcademicSubTopic"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicSubTopic"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicSubTopic"> | Date | string
}

export type AcademicSubTopicCreateInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  topic: Prisma.AcademicTopicCreateNestedOneWithoutSubtopicsInput
  mcqs?: Prisma.McqCreateNestedManyWithoutSubtopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicUncheckedCreateInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  topicId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutSubtopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  topic?: Prisma.AcademicTopicUpdateOneRequiredWithoutSubtopicsNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutSubtopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutSubtopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicCreateManyInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  topicId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicSubTopicUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicSubTopicUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicSubTopicListRelationFilter = {
  every?: Prisma.AcademicSubTopicWhereInput
  some?: Prisma.AcademicSubTopicWhereInput
  none?: Prisma.AcademicSubTopicWhereInput
}

export type AcademicSubTopicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AcademicSubTopicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSubTopicAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicSubTopicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSubTopicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  position?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  topicId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicSubTopicSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type AcademicSubTopicNullableScalarRelationFilter = {
  is?: Prisma.AcademicSubTopicWhereInput | null
  isNot?: Prisma.AcademicSubTopicWhereInput | null
}

export type AcademicSubTopicCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput> | Prisma.AcademicSubTopicCreateWithoutTopicInput[] | Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput | Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.AcademicSubTopicCreateManyTopicInputEnvelope
  connect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
}

export type AcademicSubTopicUncheckedCreateNestedManyWithoutTopicInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput> | Prisma.AcademicSubTopicCreateWithoutTopicInput[] | Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput | Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput[]
  createMany?: Prisma.AcademicSubTopicCreateManyTopicInputEnvelope
  connect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
}

export type AcademicSubTopicUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput> | Prisma.AcademicSubTopicCreateWithoutTopicInput[] | Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput | Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.AcademicSubTopicUpsertWithWhereUniqueWithoutTopicInput | Prisma.AcademicSubTopicUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.AcademicSubTopicCreateManyTopicInputEnvelope
  set?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  disconnect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  delete?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  connect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  update?: Prisma.AcademicSubTopicUpdateWithWhereUniqueWithoutTopicInput | Prisma.AcademicSubTopicUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.AcademicSubTopicUpdateManyWithWhereWithoutTopicInput | Prisma.AcademicSubTopicUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.AcademicSubTopicScalarWhereInput | Prisma.AcademicSubTopicScalarWhereInput[]
}

export type AcademicSubTopicUncheckedUpdateManyWithoutTopicNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput> | Prisma.AcademicSubTopicCreateWithoutTopicInput[] | Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput[]
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput | Prisma.AcademicSubTopicCreateOrConnectWithoutTopicInput[]
  upsert?: Prisma.AcademicSubTopicUpsertWithWhereUniqueWithoutTopicInput | Prisma.AcademicSubTopicUpsertWithWhereUniqueWithoutTopicInput[]
  createMany?: Prisma.AcademicSubTopicCreateManyTopicInputEnvelope
  set?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  disconnect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  delete?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  connect?: Prisma.AcademicSubTopicWhereUniqueInput | Prisma.AcademicSubTopicWhereUniqueInput[]
  update?: Prisma.AcademicSubTopicUpdateWithWhereUniqueWithoutTopicInput | Prisma.AcademicSubTopicUpdateWithWhereUniqueWithoutTopicInput[]
  updateMany?: Prisma.AcademicSubTopicUpdateManyWithWhereWithoutTopicInput | Prisma.AcademicSubTopicUpdateManyWithWhereWithoutTopicInput[]
  deleteMany?: Prisma.AcademicSubTopicScalarWhereInput | Prisma.AcademicSubTopicScalarWhereInput[]
}

export type AcademicSubTopicCreateNestedOneWithoutMcqsInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutMcqsInput>
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutMcqsInput
  connect?: Prisma.AcademicSubTopicWhereUniqueInput
}

export type AcademicSubTopicUpdateOneWithoutMcqsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutMcqsInput>
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutMcqsInput
  upsert?: Prisma.AcademicSubTopicUpsertWithoutMcqsInput
  disconnect?: Prisma.AcademicSubTopicWhereInput | boolean
  delete?: Prisma.AcademicSubTopicWhereInput | boolean
  connect?: Prisma.AcademicSubTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicSubTopicUpdateToOneWithWhereWithoutMcqsInput, Prisma.AcademicSubTopicUpdateWithoutMcqsInput>, Prisma.AcademicSubTopicUncheckedUpdateWithoutMcqsInput>
}

export type AcademicSubTopicCreateNestedOneWithoutCqsInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutCqsInput
  connect?: Prisma.AcademicSubTopicWhereUniqueInput
}

export type AcademicSubTopicUpdateOneWithoutCqsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutCqsInput>
  connectOrCreate?: Prisma.AcademicSubTopicCreateOrConnectWithoutCqsInput
  upsert?: Prisma.AcademicSubTopicUpsertWithoutCqsInput
  disconnect?: Prisma.AcademicSubTopicWhereInput | boolean
  delete?: Prisma.AcademicSubTopicWhereInput | boolean
  connect?: Prisma.AcademicSubTopicWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicSubTopicUpdateToOneWithWhereWithoutCqsInput, Prisma.AcademicSubTopicUpdateWithoutCqsInput>, Prisma.AcademicSubTopicUncheckedUpdateWithoutCqsInput>
}

export type AcademicSubTopicCreateWithoutTopicInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mcqs?: Prisma.McqCreateNestedManyWithoutSubtopicInput
  cqs?: Prisma.CqCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicUncheckedCreateWithoutTopicInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutSubtopicInput
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicCreateOrConnectWithoutTopicInput = {
  where: Prisma.AcademicSubTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput>
}

export type AcademicSubTopicCreateManyTopicInputEnvelope = {
  data: Prisma.AcademicSubTopicCreateManyTopicInput | Prisma.AcademicSubTopicCreateManyTopicInput[]
  skipDuplicates?: boolean
}

export type AcademicSubTopicUpsertWithWhereUniqueWithoutTopicInput = {
  where: Prisma.AcademicSubTopicWhereUniqueInput
  update: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutTopicInput>
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedCreateWithoutTopicInput>
}

export type AcademicSubTopicUpdateWithWhereUniqueWithoutTopicInput = {
  where: Prisma.AcademicSubTopicWhereUniqueInput
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutTopicInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutTopicInput>
}

export type AcademicSubTopicUpdateManyWithWhereWithoutTopicInput = {
  where: Prisma.AcademicSubTopicScalarWhereInput
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateManyMutationInput, Prisma.AcademicSubTopicUncheckedUpdateManyWithoutTopicInput>
}

export type AcademicSubTopicScalarWhereInput = {
  AND?: Prisma.AcademicSubTopicScalarWhereInput | Prisma.AcademicSubTopicScalarWhereInput[]
  OR?: Prisma.AcademicSubTopicScalarWhereInput[]
  NOT?: Prisma.AcademicSubTopicScalarWhereInput | Prisma.AcademicSubTopicScalarWhereInput[]
  id?: Prisma.StringFilter<"AcademicSubTopic"> | string
  name?: Prisma.StringFilter<"AcademicSubTopic"> | string
  displayName?: Prisma.StringFilter<"AcademicSubTopic"> | string
  position?: Prisma.IntFilter<"AcademicSubTopic"> | number
  isActive?: Prisma.BoolFilter<"AcademicSubTopic"> | boolean
  topicId?: Prisma.StringFilter<"AcademicSubTopic"> | string
  createdAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicSubTopic"> | Date | string
}

export type AcademicSubTopicCreateWithoutMcqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  topic: Prisma.AcademicTopicCreateNestedOneWithoutSubtopicsInput
  cqs?: Prisma.CqCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicUncheckedCreateWithoutMcqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  topicId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  cqs?: Prisma.CqUncheckedCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicCreateOrConnectWithoutMcqsInput = {
  where: Prisma.AcademicSubTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutMcqsInput>
}

export type AcademicSubTopicUpsertWithoutMcqsInput = {
  update: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutMcqsInput>
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutMcqsInput>
  where?: Prisma.AcademicSubTopicWhereInput
}

export type AcademicSubTopicUpdateToOneWithWhereWithoutMcqsInput = {
  where?: Prisma.AcademicSubTopicWhereInput
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutMcqsInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutMcqsInput>
}

export type AcademicSubTopicUpdateWithoutMcqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  topic?: Prisma.AcademicTopicUpdateOneRequiredWithoutSubtopicsNestedInput
  cqs?: Prisma.CqUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicUncheckedUpdateWithoutMcqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cqs?: Prisma.CqUncheckedUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicCreateWithoutCqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  topic: Prisma.AcademicTopicCreateNestedOneWithoutSubtopicsInput
  mcqs?: Prisma.McqCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicUncheckedCreateWithoutCqsInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  topicId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  mcqs?: Prisma.McqUncheckedCreateNestedManyWithoutSubtopicInput
}

export type AcademicSubTopicCreateOrConnectWithoutCqsInput = {
  where: Prisma.AcademicSubTopicWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutCqsInput>
}

export type AcademicSubTopicUpsertWithoutCqsInput = {
  update: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutCqsInput>
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedCreateWithoutCqsInput>
  where?: Prisma.AcademicSubTopicWhereInput
}

export type AcademicSubTopicUpdateToOneWithWhereWithoutCqsInput = {
  where?: Prisma.AcademicSubTopicWhereInput
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateWithoutCqsInput, Prisma.AcademicSubTopicUncheckedUpdateWithoutCqsInput>
}

export type AcademicSubTopicUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  topic?: Prisma.AcademicTopicUpdateOneRequiredWithoutSubtopicsNestedInput
  mcqs?: Prisma.McqUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicUncheckedUpdateWithoutCqsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  topicId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicCreateManyTopicInput = {
  id?: string
  name: string
  displayName: string
  position?: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicSubTopicUpdateWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcqs?: Prisma.McqUpdateManyWithoutSubtopicNestedInput
  cqs?: Prisma.CqUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicUncheckedUpdateWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  mcqs?: Prisma.McqUncheckedUpdateManyWithoutSubtopicNestedInput
  cqs?: Prisma.CqUncheckedUpdateManyWithoutSubtopicNestedInput
}

export type AcademicSubTopicUncheckedUpdateManyWithoutTopicInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AcademicSubTopicCountOutputType
 */

export type AcademicSubTopicCountOutputType = {
  mcqs: number
  cqs: number
}

export type AcademicSubTopicCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mcqs?: boolean | AcademicSubTopicCountOutputTypeCountMcqsArgs
  cqs?: boolean | AcademicSubTopicCountOutputTypeCountCqsArgs
}

/**
 * AcademicSubTopicCountOutputType without action
 */
export type AcademicSubTopicCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopicCountOutputType
   */
  select?: Prisma.AcademicSubTopicCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AcademicSubTopicCountOutputType without action
 */
export type AcademicSubTopicCountOutputTypeCountMcqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.McqWhereInput
}

/**
 * AcademicSubTopicCountOutputType without action
 */
export type AcademicSubTopicCountOutputTypeCountCqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CqWhereInput
}


export type AcademicSubTopicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  topicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
  mcqs?: boolean | Prisma.AcademicSubTopic$mcqsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicSubTopic$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicSubTopicCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSubTopic"]>

export type AcademicSubTopicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  topicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSubTopic"]>

export type AcademicSubTopicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  topicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicSubTopic"]>

export type AcademicSubTopicSelectScalar = {
  id?: boolean
  name?: boolean
  displayName?: boolean
  position?: boolean
  isActive?: boolean
  topicId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AcademicSubTopicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "displayName" | "position" | "isActive" | "topicId" | "createdAt" | "updatedAt", ExtArgs["result"]["academicSubTopic"]>
export type AcademicSubTopicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
  mcqs?: boolean | Prisma.AcademicSubTopic$mcqsArgs<ExtArgs>
  cqs?: boolean | Prisma.AcademicSubTopic$cqsArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicSubTopicCountOutputTypeDefaultArgs<ExtArgs>
}
export type AcademicSubTopicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
}
export type AcademicSubTopicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topic?: boolean | Prisma.AcademicTopicDefaultArgs<ExtArgs>
}

export type $AcademicSubTopicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AcademicSubTopic"
  objects: {
    topic: Prisma.$AcademicTopicPayload<ExtArgs>
    mcqs: Prisma.$McqPayload<ExtArgs>[]
    cqs: Prisma.$CqPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    displayName: string
    position: number
    isActive: boolean
    topicId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["academicSubTopic"]>
  composites: {}
}

export type AcademicSubTopicGetPayload<S extends boolean | null | undefined | AcademicSubTopicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload, S>

export type AcademicSubTopicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AcademicSubTopicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AcademicSubTopicCountAggregateInputType | true
  }

export interface AcademicSubTopicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AcademicSubTopic'], meta: { name: 'AcademicSubTopic' } }
  /**
   * Find zero or one AcademicSubTopic that matches the filter.
   * @param {AcademicSubTopicFindUniqueArgs} args - Arguments to find a AcademicSubTopic
   * @example
   * // Get one AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AcademicSubTopicFindUniqueArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AcademicSubTopic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AcademicSubTopicFindUniqueOrThrowArgs} args - Arguments to find a AcademicSubTopic
   * @example
   * // Get one AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AcademicSubTopicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicSubTopic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicFindFirstArgs} args - Arguments to find a AcademicSubTopic
   * @example
   * // Get one AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AcademicSubTopicFindFirstArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicFindFirstArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicSubTopic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicFindFirstOrThrowArgs} args - Arguments to find a AcademicSubTopic
   * @example
   * // Get one AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AcademicSubTopicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AcademicSubTopics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AcademicSubTopics
   * const academicSubTopics = await prisma.academicSubTopic.findMany()
   * 
   * // Get first 10 AcademicSubTopics
   * const academicSubTopics = await prisma.academicSubTopic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const academicSubTopicWithIdOnly = await prisma.academicSubTopic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AcademicSubTopicFindManyArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AcademicSubTopic.
   * @param {AcademicSubTopicCreateArgs} args - Arguments to create a AcademicSubTopic.
   * @example
   * // Create one AcademicSubTopic
   * const AcademicSubTopic = await prisma.academicSubTopic.create({
   *   data: {
   *     // ... data to create a AcademicSubTopic
   *   }
   * })
   * 
   */
  create<T extends AcademicSubTopicCreateArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicCreateArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AcademicSubTopics.
   * @param {AcademicSubTopicCreateManyArgs} args - Arguments to create many AcademicSubTopics.
   * @example
   * // Create many AcademicSubTopics
   * const academicSubTopic = await prisma.academicSubTopic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AcademicSubTopicCreateManyArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AcademicSubTopics and returns the data saved in the database.
   * @param {AcademicSubTopicCreateManyAndReturnArgs} args - Arguments to create many AcademicSubTopics.
   * @example
   * // Create many AcademicSubTopics
   * const academicSubTopic = await prisma.academicSubTopic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AcademicSubTopics and only return the `id`
   * const academicSubTopicWithIdOnly = await prisma.academicSubTopic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AcademicSubTopicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AcademicSubTopic.
   * @param {AcademicSubTopicDeleteArgs} args - Arguments to delete one AcademicSubTopic.
   * @example
   * // Delete one AcademicSubTopic
   * const AcademicSubTopic = await prisma.academicSubTopic.delete({
   *   where: {
   *     // ... filter to delete one AcademicSubTopic
   *   }
   * })
   * 
   */
  delete<T extends AcademicSubTopicDeleteArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicDeleteArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AcademicSubTopic.
   * @param {AcademicSubTopicUpdateArgs} args - Arguments to update one AcademicSubTopic.
   * @example
   * // Update one AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AcademicSubTopicUpdateArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicUpdateArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AcademicSubTopics.
   * @param {AcademicSubTopicDeleteManyArgs} args - Arguments to filter AcademicSubTopics to delete.
   * @example
   * // Delete a few AcademicSubTopics
   * const { count } = await prisma.academicSubTopic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AcademicSubTopicDeleteManyArgs>(args?: Prisma.SelectSubset<T, AcademicSubTopicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicSubTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AcademicSubTopics
   * const academicSubTopic = await prisma.academicSubTopic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AcademicSubTopicUpdateManyArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicSubTopics and returns the data updated in the database.
   * @param {AcademicSubTopicUpdateManyAndReturnArgs} args - Arguments to update many AcademicSubTopics.
   * @example
   * // Update many AcademicSubTopics
   * const academicSubTopic = await prisma.academicSubTopic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AcademicSubTopics and only return the `id`
   * const academicSubTopicWithIdOnly = await prisma.academicSubTopic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AcademicSubTopicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AcademicSubTopic.
   * @param {AcademicSubTopicUpsertArgs} args - Arguments to update or create a AcademicSubTopic.
   * @example
   * // Update or create a AcademicSubTopic
   * const academicSubTopic = await prisma.academicSubTopic.upsert({
   *   create: {
   *     // ... data to create a AcademicSubTopic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AcademicSubTopic we want to update
   *   }
   * })
   */
  upsert<T extends AcademicSubTopicUpsertArgs>(args: Prisma.SelectSubset<T, AcademicSubTopicUpsertArgs<ExtArgs>>): Prisma.Prisma__AcademicSubTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicSubTopicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AcademicSubTopics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicCountArgs} args - Arguments to filter AcademicSubTopics to count.
   * @example
   * // Count the number of AcademicSubTopics
   * const count = await prisma.academicSubTopic.count({
   *   where: {
   *     // ... the filter for the AcademicSubTopics we want to count
   *   }
   * })
  **/
  count<T extends AcademicSubTopicCountArgs>(
    args?: Prisma.Subset<T, AcademicSubTopicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AcademicSubTopicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AcademicSubTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AcademicSubTopicAggregateArgs>(args: Prisma.Subset<T, AcademicSubTopicAggregateArgs>): Prisma.PrismaPromise<GetAcademicSubTopicAggregateType<T>>

  /**
   * Group by AcademicSubTopic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicSubTopicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AcademicSubTopicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AcademicSubTopicGroupByArgs['orderBy'] }
      : { orderBy?: AcademicSubTopicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AcademicSubTopicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAcademicSubTopicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AcademicSubTopic model
 */
readonly fields: AcademicSubTopicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AcademicSubTopic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AcademicSubTopicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  topic<T extends Prisma.AcademicTopicDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicTopicDefaultArgs<ExtArgs>>): Prisma.Prisma__AcademicTopicClient<runtime.Types.Result.GetResult<Prisma.$AcademicTopicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  mcqs<T extends Prisma.AcademicSubTopic$mcqsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicSubTopic$mcqsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$McqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cqs<T extends Prisma.AcademicSubTopic$cqsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicSubTopic$cqsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AcademicSubTopic model
 */
export interface AcademicSubTopicFieldRefs {
  readonly id: Prisma.FieldRef<"AcademicSubTopic", 'String'>
  readonly name: Prisma.FieldRef<"AcademicSubTopic", 'String'>
  readonly displayName: Prisma.FieldRef<"AcademicSubTopic", 'String'>
  readonly position: Prisma.FieldRef<"AcademicSubTopic", 'Int'>
  readonly isActive: Prisma.FieldRef<"AcademicSubTopic", 'Boolean'>
  readonly topicId: Prisma.FieldRef<"AcademicSubTopic", 'String'>
  readonly createdAt: Prisma.FieldRef<"AcademicSubTopic", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AcademicSubTopic", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AcademicSubTopic findUnique
 */
export type AcademicSubTopicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSubTopic to fetch.
   */
  where: Prisma.AcademicSubTopicWhereUniqueInput
}

/**
 * AcademicSubTopic findUniqueOrThrow
 */
export type AcademicSubTopicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSubTopic to fetch.
   */
  where: Prisma.AcademicSubTopicWhereUniqueInput
}

/**
 * AcademicSubTopic findFirst
 */
export type AcademicSubTopicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSubTopic to fetch.
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSubTopics to fetch.
   */
  orderBy?: Prisma.AcademicSubTopicOrderByWithRelationInput | Prisma.AcademicSubTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicSubTopics.
   */
  cursor?: Prisma.AcademicSubTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSubTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSubTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicSubTopics.
   */
  distinct?: Prisma.AcademicSubTopicScalarFieldEnum | Prisma.AcademicSubTopicScalarFieldEnum[]
}

/**
 * AcademicSubTopic findFirstOrThrow
 */
export type AcademicSubTopicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSubTopic to fetch.
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSubTopics to fetch.
   */
  orderBy?: Prisma.AcademicSubTopicOrderByWithRelationInput | Prisma.AcademicSubTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicSubTopics.
   */
  cursor?: Prisma.AcademicSubTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSubTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSubTopics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicSubTopics.
   */
  distinct?: Prisma.AcademicSubTopicScalarFieldEnum | Prisma.AcademicSubTopicScalarFieldEnum[]
}

/**
 * AcademicSubTopic findMany
 */
export type AcademicSubTopicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter, which AcademicSubTopics to fetch.
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicSubTopics to fetch.
   */
  orderBy?: Prisma.AcademicSubTopicOrderByWithRelationInput | Prisma.AcademicSubTopicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AcademicSubTopics.
   */
  cursor?: Prisma.AcademicSubTopicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicSubTopics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicSubTopics.
   */
  skip?: number
  distinct?: Prisma.AcademicSubTopicScalarFieldEnum | Prisma.AcademicSubTopicScalarFieldEnum[]
}

/**
 * AcademicSubTopic create
 */
export type AcademicSubTopicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * The data needed to create a AcademicSubTopic.
   */
  data: Prisma.XOR<Prisma.AcademicSubTopicCreateInput, Prisma.AcademicSubTopicUncheckedCreateInput>
}

/**
 * AcademicSubTopic createMany
 */
export type AcademicSubTopicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AcademicSubTopics.
   */
  data: Prisma.AcademicSubTopicCreateManyInput | Prisma.AcademicSubTopicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicSubTopic createManyAndReturn
 */
export type AcademicSubTopicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * The data used to create many AcademicSubTopics.
   */
  data: Prisma.AcademicSubTopicCreateManyInput | Prisma.AcademicSubTopicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicSubTopic update
 */
export type AcademicSubTopicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * The data needed to update a AcademicSubTopic.
   */
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateInput, Prisma.AcademicSubTopicUncheckedUpdateInput>
  /**
   * Choose, which AcademicSubTopic to update.
   */
  where: Prisma.AcademicSubTopicWhereUniqueInput
}

/**
 * AcademicSubTopic updateMany
 */
export type AcademicSubTopicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AcademicSubTopics.
   */
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateManyMutationInput, Prisma.AcademicSubTopicUncheckedUpdateManyInput>
  /**
   * Filter which AcademicSubTopics to update
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * Limit how many AcademicSubTopics to update.
   */
  limit?: number
}

/**
 * AcademicSubTopic updateManyAndReturn
 */
export type AcademicSubTopicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * The data used to update AcademicSubTopics.
   */
  data: Prisma.XOR<Prisma.AcademicSubTopicUpdateManyMutationInput, Prisma.AcademicSubTopicUncheckedUpdateManyInput>
  /**
   * Filter which AcademicSubTopics to update
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * Limit how many AcademicSubTopics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AcademicSubTopic upsert
 */
export type AcademicSubTopicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * The filter to search for the AcademicSubTopic to update in case it exists.
   */
  where: Prisma.AcademicSubTopicWhereUniqueInput
  /**
   * In case the AcademicSubTopic found by the `where` argument doesn't exist, create a new AcademicSubTopic with this data.
   */
  create: Prisma.XOR<Prisma.AcademicSubTopicCreateInput, Prisma.AcademicSubTopicUncheckedCreateInput>
  /**
   * In case the AcademicSubTopic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AcademicSubTopicUpdateInput, Prisma.AcademicSubTopicUncheckedUpdateInput>
}

/**
 * AcademicSubTopic delete
 */
export type AcademicSubTopicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
  /**
   * Filter which AcademicSubTopic to delete.
   */
  where: Prisma.AcademicSubTopicWhereUniqueInput
}

/**
 * AcademicSubTopic deleteMany
 */
export type AcademicSubTopicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicSubTopics to delete
   */
  where?: Prisma.AcademicSubTopicWhereInput
  /**
   * Limit how many AcademicSubTopics to delete.
   */
  limit?: number
}

/**
 * AcademicSubTopic.mcqs
 */
export type AcademicSubTopic$mcqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mcq
   */
  select?: Prisma.McqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mcq
   */
  omit?: Prisma.McqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.McqInclude<ExtArgs> | null
  where?: Prisma.McqWhereInput
  orderBy?: Prisma.McqOrderByWithRelationInput | Prisma.McqOrderByWithRelationInput[]
  cursor?: Prisma.McqWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.McqScalarFieldEnum | Prisma.McqScalarFieldEnum[]
}

/**
 * AcademicSubTopic.cqs
 */
export type AcademicSubTopic$cqsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cq
   */
  select?: Prisma.CqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cq
   */
  omit?: Prisma.CqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqInclude<ExtArgs> | null
  where?: Prisma.CqWhereInput
  orderBy?: Prisma.CqOrderByWithRelationInput | Prisma.CqOrderByWithRelationInput[]
  cursor?: Prisma.CqWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CqScalarFieldEnum | Prisma.CqScalarFieldEnum[]
}

/**
 * AcademicSubTopic without action
 */
export type AcademicSubTopicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubTopic
   */
  select?: Prisma.AcademicSubTopicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubTopic
   */
  omit?: Prisma.AcademicSubTopicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubTopicInclude<ExtArgs> | null
}
