
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AcademicYear` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AcademicYear
 * 
 */
export type AcademicYearModel = runtime.Types.Result.DefaultSelection<Prisma.$AcademicYearPayload>

export type AggregateAcademicYear = {
  _count: AcademicYearCountAggregateOutputType | null
  _min: AcademicYearMinAggregateOutputType | null
  _max: AcademicYearMaxAggregateOutputType | null
}

export type AcademicYearMinAggregateOutputType = {
  id: string | null
  label: string | null
  slug: string | null
  startDate: Date | null
  endDate: Date | null
  isCurrent: boolean | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicYearMaxAggregateOutputType = {
  id: string | null
  label: string | null
  slug: string | null
  startDate: Date | null
  endDate: Date | null
  isCurrent: boolean | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AcademicYearCountAggregateOutputType = {
  id: number
  label: number
  slug: number
  startDate: number
  endDate: number
  isCurrent: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AcademicYearMinAggregateInputType = {
  id?: true
  label?: true
  slug?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicYearMaxAggregateInputType = {
  id?: true
  label?: true
  slug?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type AcademicYearCountAggregateInputType = {
  id?: true
  label?: true
  slug?: true
  startDate?: true
  endDate?: true
  isCurrent?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AcademicYearAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicYear to aggregate.
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicYears to fetch.
   */
  orderBy?: Prisma.AcademicYearOrderByWithRelationInput | Prisma.AcademicYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AcademicYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AcademicYears
  **/
  _count?: true | AcademicYearCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AcademicYearMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AcademicYearMaxAggregateInputType
}

export type GetAcademicYearAggregateType<T extends AcademicYearAggregateArgs> = {
      [P in keyof T & keyof AggregateAcademicYear]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAcademicYear[P]>
    : Prisma.GetScalarType<T[P], AggregateAcademicYear[P]>
}




export type AcademicYearGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicYearWhereInput
  orderBy?: Prisma.AcademicYearOrderByWithAggregationInput | Prisma.AcademicYearOrderByWithAggregationInput[]
  by: Prisma.AcademicYearScalarFieldEnum[] | Prisma.AcademicYearScalarFieldEnum
  having?: Prisma.AcademicYearScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AcademicYearCountAggregateInputType | true
  _min?: AcademicYearMinAggregateInputType
  _max?: AcademicYearMaxAggregateInputType
}

export type AcademicYearGroupByOutputType = {
  id: string
  label: string
  slug: string
  startDate: Date
  endDate: Date
  isCurrent: boolean
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: AcademicYearCountAggregateOutputType | null
  _min: AcademicYearMinAggregateOutputType | null
  _max: AcademicYearMaxAggregateOutputType | null
}

type GetAcademicYearGroupByPayload<T extends AcademicYearGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AcademicYearGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AcademicYearGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AcademicYearGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AcademicYearGroupByOutputType[P]>
      }
    >
  >



export type AcademicYearWhereInput = {
  AND?: Prisma.AcademicYearWhereInput | Prisma.AcademicYearWhereInput[]
  OR?: Prisma.AcademicYearWhereInput[]
  NOT?: Prisma.AcademicYearWhereInput | Prisma.AcademicYearWhereInput[]
  id?: Prisma.StringFilter<"AcademicYear"> | string
  label?: Prisma.StringFilter<"AcademicYear"> | string
  slug?: Prisma.StringFilter<"AcademicYear"> | string
  startDate?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  endDate?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  isCurrent?: Prisma.BoolFilter<"AcademicYear"> | boolean
  isActive?: Prisma.BoolFilter<"AcademicYear"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  sessions?: Prisma.AcademicSessionListRelationFilter
  tenants?: Prisma.TenantListRelationFilter
  questionPapers?: Prisma.QuestionPaperListRelationFilter
  subjects?: Prisma.AcademicSubjectListRelationFilter
  chapters?: Prisma.AcademicChapterListRelationFilter
}

export type AcademicYearOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  sessions?: Prisma.AcademicSessionOrderByRelationAggregateInput
  tenants?: Prisma.TenantOrderByRelationAggregateInput
  questionPapers?: Prisma.QuestionPaperOrderByRelationAggregateInput
  subjects?: Prisma.AcademicSubjectOrderByRelationAggregateInput
  chapters?: Prisma.AcademicChapterOrderByRelationAggregateInput
}

export type AcademicYearWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  label?: string
  slug?: string
  AND?: Prisma.AcademicYearWhereInput | Prisma.AcademicYearWhereInput[]
  OR?: Prisma.AcademicYearWhereInput[]
  NOT?: Prisma.AcademicYearWhereInput | Prisma.AcademicYearWhereInput[]
  startDate?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  endDate?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  isCurrent?: Prisma.BoolFilter<"AcademicYear"> | boolean
  isActive?: Prisma.BoolFilter<"AcademicYear"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AcademicYear"> | Date | string
  sessions?: Prisma.AcademicSessionListRelationFilter
  tenants?: Prisma.TenantListRelationFilter
  questionPapers?: Prisma.QuestionPaperListRelationFilter
  subjects?: Prisma.AcademicSubjectListRelationFilter
  chapters?: Prisma.AcademicChapterListRelationFilter
}, "id" | "label" | "slug">

export type AcademicYearOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AcademicYearCountOrderByAggregateInput
  _max?: Prisma.AcademicYearMaxOrderByAggregateInput
  _min?: Prisma.AcademicYearMinOrderByAggregateInput
}

export type AcademicYearScalarWhereWithAggregatesInput = {
  AND?: Prisma.AcademicYearScalarWhereWithAggregatesInput | Prisma.AcademicYearScalarWhereWithAggregatesInput[]
  OR?: Prisma.AcademicYearScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AcademicYearScalarWhereWithAggregatesInput | Prisma.AcademicYearScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AcademicYear"> | string
  label?: Prisma.StringWithAggregatesFilter<"AcademicYear"> | string
  slug?: Prisma.StringWithAggregatesFilter<"AcademicYear"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"AcademicYear"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"AcademicYear"> | Date | string
  isCurrent?: Prisma.BoolWithAggregatesFilter<"AcademicYear"> | boolean
  isActive?: Prisma.BoolWithAggregatesFilter<"AcademicYear"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicYear"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AcademicYear"> | Date | string
}

export type AcademicYearCreateInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperUncheckedCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUncheckedUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUncheckedUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearCreateManyInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AcademicYearUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicYearUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AcademicYearNullableScalarRelationFilter = {
  is?: Prisma.AcademicYearWhereInput | null
  isNot?: Prisma.AcademicYearWhereInput | null
}

export type AcademicYearScalarRelationFilter = {
  is?: Prisma.AcademicYearWhereInput
  isNot?: Prisma.AcademicYearWhereInput
}

export type AcademicYearCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicYearMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicYearMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AcademicYearCreateNestedOneWithoutTenantsInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutTenantsInput, Prisma.AcademicYearUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutTenantsInput
  connect?: Prisma.AcademicYearWhereUniqueInput
}

export type AcademicYearUpdateOneWithoutTenantsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutTenantsInput, Prisma.AcademicYearUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutTenantsInput
  upsert?: Prisma.AcademicYearUpsertWithoutTenantsInput
  disconnect?: Prisma.AcademicYearWhereInput | boolean
  delete?: Prisma.AcademicYearWhereInput | boolean
  connect?: Prisma.AcademicYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicYearUpdateToOneWithWhereWithoutTenantsInput, Prisma.AcademicYearUpdateWithoutTenantsInput>, Prisma.AcademicYearUncheckedUpdateWithoutTenantsInput>
}

export type AcademicYearCreateNestedOneWithoutSubjectsInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutSubjectsInput, Prisma.AcademicYearUncheckedCreateWithoutSubjectsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutSubjectsInput
  connect?: Prisma.AcademicYearWhereUniqueInput
}

export type AcademicYearUpdateOneRequiredWithoutSubjectsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutSubjectsInput, Prisma.AcademicYearUncheckedCreateWithoutSubjectsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutSubjectsInput
  upsert?: Prisma.AcademicYearUpsertWithoutSubjectsInput
  connect?: Prisma.AcademicYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicYearUpdateToOneWithWhereWithoutSubjectsInput, Prisma.AcademicYearUpdateWithoutSubjectsInput>, Prisma.AcademicYearUncheckedUpdateWithoutSubjectsInput>
}

export type AcademicYearCreateNestedOneWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutChaptersInput, Prisma.AcademicYearUncheckedCreateWithoutChaptersInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutChaptersInput
  connect?: Prisma.AcademicYearWhereUniqueInput
}

export type AcademicYearUpdateOneRequiredWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutChaptersInput, Prisma.AcademicYearUncheckedCreateWithoutChaptersInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutChaptersInput
  upsert?: Prisma.AcademicYearUpsertWithoutChaptersInput
  connect?: Prisma.AcademicYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicYearUpdateToOneWithWhereWithoutChaptersInput, Prisma.AcademicYearUpdateWithoutChaptersInput>, Prisma.AcademicYearUncheckedUpdateWithoutChaptersInput>
}

export type AcademicYearCreateNestedOneWithoutQuestionPapersInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedCreateWithoutQuestionPapersInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutQuestionPapersInput
  connect?: Prisma.AcademicYearWhereUniqueInput
}

export type AcademicYearUpdateOneWithoutQuestionPapersNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedCreateWithoutQuestionPapersInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutQuestionPapersInput
  upsert?: Prisma.AcademicYearUpsertWithoutQuestionPapersInput
  disconnect?: Prisma.AcademicYearWhereInput | boolean
  delete?: Prisma.AcademicYearWhereInput | boolean
  connect?: Prisma.AcademicYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicYearUpdateToOneWithWhereWithoutQuestionPapersInput, Prisma.AcademicYearUpdateWithoutQuestionPapersInput>, Prisma.AcademicYearUncheckedUpdateWithoutQuestionPapersInput>
}

export type AcademicYearCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutSessionsInput, Prisma.AcademicYearUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutSessionsInput
  connect?: Prisma.AcademicYearWhereUniqueInput
}

export type AcademicYearUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.AcademicYearCreateWithoutSessionsInput, Prisma.AcademicYearUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AcademicYearCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.AcademicYearUpsertWithoutSessionsInput
  connect?: Prisma.AcademicYearWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AcademicYearUpdateToOneWithWhereWithoutSessionsInput, Prisma.AcademicYearUpdateWithoutSessionsInput>, Prisma.AcademicYearUncheckedUpdateWithoutSessionsInput>
}

export type AcademicYearCreateWithoutTenantsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionCreateNestedManyWithoutAcademicYearInput
  questionPapers?: Prisma.QuestionPaperCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateWithoutTenantsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput
  questionPapers?: Prisma.QuestionPaperUncheckedCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearCreateOrConnectWithoutTenantsInput = {
  where: Prisma.AcademicYearWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutTenantsInput, Prisma.AcademicYearUncheckedCreateWithoutTenantsInput>
}

export type AcademicYearUpsertWithoutTenantsInput = {
  update: Prisma.XOR<Prisma.AcademicYearUpdateWithoutTenantsInput, Prisma.AcademicYearUncheckedUpdateWithoutTenantsInput>
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutTenantsInput, Prisma.AcademicYearUncheckedCreateWithoutTenantsInput>
  where?: Prisma.AcademicYearWhereInput
}

export type AcademicYearUpdateToOneWithWhereWithoutTenantsInput = {
  where?: Prisma.AcademicYearWhereInput
  data: Prisma.XOR<Prisma.AcademicYearUpdateWithoutTenantsInput, Prisma.AcademicYearUncheckedUpdateWithoutTenantsInput>
}

export type AcademicYearUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUpdateManyWithoutAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUncheckedUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUncheckedUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearCreateWithoutSubjectsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateWithoutSubjectsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperUncheckedCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearCreateOrConnectWithoutSubjectsInput = {
  where: Prisma.AcademicYearWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutSubjectsInput, Prisma.AcademicYearUncheckedCreateWithoutSubjectsInput>
}

export type AcademicYearUpsertWithoutSubjectsInput = {
  update: Prisma.XOR<Prisma.AcademicYearUpdateWithoutSubjectsInput, Prisma.AcademicYearUncheckedUpdateWithoutSubjectsInput>
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutSubjectsInput, Prisma.AcademicYearUncheckedCreateWithoutSubjectsInput>
  where?: Prisma.AcademicYearWhereInput
}

export type AcademicYearUpdateToOneWithWhereWithoutSubjectsInput = {
  where?: Prisma.AcademicYearWhereInput
  data: Prisma.XOR<Prisma.AcademicYearUpdateWithoutSubjectsInput, Prisma.AcademicYearUncheckedUpdateWithoutSubjectsInput>
}

export type AcademicYearUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateWithoutSubjectsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUncheckedUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUncheckedUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearCreateWithoutChaptersInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateWithoutChaptersInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperUncheckedCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearCreateOrConnectWithoutChaptersInput = {
  where: Prisma.AcademicYearWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutChaptersInput, Prisma.AcademicYearUncheckedCreateWithoutChaptersInput>
}

export type AcademicYearUpsertWithoutChaptersInput = {
  update: Prisma.XOR<Prisma.AcademicYearUpdateWithoutChaptersInput, Prisma.AcademicYearUncheckedUpdateWithoutChaptersInput>
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutChaptersInput, Prisma.AcademicYearUncheckedCreateWithoutChaptersInput>
  where?: Prisma.AcademicYearWhereInput
}

export type AcademicYearUpdateToOneWithWhereWithoutChaptersInput = {
  where?: Prisma.AcademicYearWhereInput
  data: Prisma.XOR<Prisma.AcademicYearUpdateWithoutChaptersInput, Prisma.AcademicYearUncheckedUpdateWithoutChaptersInput>
}

export type AcademicYearUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUncheckedUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearCreateWithoutQuestionPapersInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantCreateNestedManyWithoutCurrentAcademicYearInput
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateWithoutQuestionPapersInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.AcademicSessionUncheckedCreateNestedManyWithoutAcademicYearInput
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutCurrentAcademicYearInput
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearCreateOrConnectWithoutQuestionPapersInput = {
  where: Prisma.AcademicYearWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedCreateWithoutQuestionPapersInput>
}

export type AcademicYearUpsertWithoutQuestionPapersInput = {
  update: Prisma.XOR<Prisma.AcademicYearUpdateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedUpdateWithoutQuestionPapersInput>
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedCreateWithoutQuestionPapersInput>
  where?: Prisma.AcademicYearWhereInput
}

export type AcademicYearUpdateToOneWithWhereWithoutQuestionPapersInput = {
  where?: Prisma.AcademicYearWhereInput
  data: Prisma.XOR<Prisma.AcademicYearUpdateWithoutQuestionPapersInput, Prisma.AcademicYearUncheckedUpdateWithoutQuestionPapersInput>
}

export type AcademicYearUpdateWithoutQuestionPapersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUpdateManyWithoutCurrentAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateWithoutQuestionPapersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.AcademicSessionUncheckedUpdateManyWithoutAcademicYearNestedInput
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutCurrentAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUncheckedUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearCreateWithoutSessionsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  tenants?: Prisma.TenantCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearUncheckedCreateWithoutSessionsInput = {
  id?: string
  label: string
  slug: string
  startDate: Date | string
  endDate: Date | string
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  tenants?: Prisma.TenantUncheckedCreateNestedManyWithoutCurrentAcademicYearInput
  questionPapers?: Prisma.QuestionPaperUncheckedCreateNestedManyWithoutAcademicYearInput
  subjects?: Prisma.AcademicSubjectUncheckedCreateNestedManyWithoutAcademicYearInput
  chapters?: Prisma.AcademicChapterUncheckedCreateNestedManyWithoutAcademicYearInput
}

export type AcademicYearCreateOrConnectWithoutSessionsInput = {
  where: Prisma.AcademicYearWhereUniqueInput
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutSessionsInput, Prisma.AcademicYearUncheckedCreateWithoutSessionsInput>
}

export type AcademicYearUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.AcademicYearUpdateWithoutSessionsInput, Prisma.AcademicYearUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.AcademicYearCreateWithoutSessionsInput, Prisma.AcademicYearUncheckedCreateWithoutSessionsInput>
  where?: Prisma.AcademicYearWhereInput
}

export type AcademicYearUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.AcademicYearWhereInput
  data: Prisma.XOR<Prisma.AcademicYearUpdateWithoutSessionsInput, Prisma.AcademicYearUncheckedUpdateWithoutSessionsInput>
}

export type AcademicYearUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenants?: Prisma.TenantUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUpdateManyWithoutAcademicYearNestedInput
}

export type AcademicYearUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isCurrent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenants?: Prisma.TenantUncheckedUpdateManyWithoutCurrentAcademicYearNestedInput
  questionPapers?: Prisma.QuestionPaperUncheckedUpdateManyWithoutAcademicYearNestedInput
  subjects?: Prisma.AcademicSubjectUncheckedUpdateManyWithoutAcademicYearNestedInput
  chapters?: Prisma.AcademicChapterUncheckedUpdateManyWithoutAcademicYearNestedInput
}


/**
 * Count Type AcademicYearCountOutputType
 */

export type AcademicYearCountOutputType = {
  sessions: number
  tenants: number
  questionPapers: number
  subjects: number
  chapters: number
}

export type AcademicYearCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | AcademicYearCountOutputTypeCountSessionsArgs
  tenants?: boolean | AcademicYearCountOutputTypeCountTenantsArgs
  questionPapers?: boolean | AcademicYearCountOutputTypeCountQuestionPapersArgs
  subjects?: boolean | AcademicYearCountOutputTypeCountSubjectsArgs
  chapters?: boolean | AcademicYearCountOutputTypeCountChaptersArgs
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYearCountOutputType
   */
  select?: Prisma.AcademicYearCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSessionWhereInput
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeCountTenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantWhereInput
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeCountQuestionPapersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionPaperWhereInput
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeCountSubjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicSubjectWhereInput
}

/**
 * AcademicYearCountOutputType without action
 */
export type AcademicYearCountOutputTypeCountChaptersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AcademicChapterWhereInput
}


export type AcademicYearSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  slug?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  sessions?: boolean | Prisma.AcademicYear$sessionsArgs<ExtArgs>
  tenants?: boolean | Prisma.AcademicYear$tenantsArgs<ExtArgs>
  questionPapers?: boolean | Prisma.AcademicYear$questionPapersArgs<ExtArgs>
  subjects?: boolean | Prisma.AcademicYear$subjectsArgs<ExtArgs>
  chapters?: boolean | Prisma.AcademicYear$chaptersArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicYearCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["academicYear"]>

export type AcademicYearSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  slug?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["academicYear"]>

export type AcademicYearSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  slug?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["academicYear"]>

export type AcademicYearSelectScalar = {
  id?: boolean
  label?: boolean
  slug?: boolean
  startDate?: boolean
  endDate?: boolean
  isCurrent?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AcademicYearOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "label" | "slug" | "startDate" | "endDate" | "isCurrent" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["academicYear"]>
export type AcademicYearInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | Prisma.AcademicYear$sessionsArgs<ExtArgs>
  tenants?: boolean | Prisma.AcademicYear$tenantsArgs<ExtArgs>
  questionPapers?: boolean | Prisma.AcademicYear$questionPapersArgs<ExtArgs>
  subjects?: boolean | Prisma.AcademicYear$subjectsArgs<ExtArgs>
  chapters?: boolean | Prisma.AcademicYear$chaptersArgs<ExtArgs>
  _count?: boolean | Prisma.AcademicYearCountOutputTypeDefaultArgs<ExtArgs>
}
export type AcademicYearIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AcademicYearIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AcademicYearPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AcademicYear"
  objects: {
    sessions: Prisma.$AcademicSessionPayload<ExtArgs>[]
    tenants: Prisma.$TenantPayload<ExtArgs>[]
    questionPapers: Prisma.$QuestionPaperPayload<ExtArgs>[]
    subjects: Prisma.$AcademicSubjectPayload<ExtArgs>[]
    chapters: Prisma.$AcademicChapterPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    label: string
    slug: string
    startDate: Date
    endDate: Date
    isCurrent: boolean
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["academicYear"]>
  composites: {}
}

export type AcademicYearGetPayload<S extends boolean | null | undefined | AcademicYearDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload, S>

export type AcademicYearCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AcademicYearFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AcademicYearCountAggregateInputType | true
  }

export interface AcademicYearDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AcademicYear'], meta: { name: 'AcademicYear' } }
  /**
   * Find zero or one AcademicYear that matches the filter.
   * @param {AcademicYearFindUniqueArgs} args - Arguments to find a AcademicYear
   * @example
   * // Get one AcademicYear
   * const academicYear = await prisma.academicYear.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AcademicYearFindUniqueArgs>(args: Prisma.SelectSubset<T, AcademicYearFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AcademicYear that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AcademicYearFindUniqueOrThrowArgs} args - Arguments to find a AcademicYear
   * @example
   * // Get one AcademicYear
   * const academicYear = await prisma.academicYear.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AcademicYearFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AcademicYearFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicYear that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearFindFirstArgs} args - Arguments to find a AcademicYear
   * @example
   * // Get one AcademicYear
   * const academicYear = await prisma.academicYear.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AcademicYearFindFirstArgs>(args?: Prisma.SelectSubset<T, AcademicYearFindFirstArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AcademicYear that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearFindFirstOrThrowArgs} args - Arguments to find a AcademicYear
   * @example
   * // Get one AcademicYear
   * const academicYear = await prisma.academicYear.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AcademicYearFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AcademicYearFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AcademicYears that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AcademicYears
   * const academicYears = await prisma.academicYear.findMany()
   * 
   * // Get first 10 AcademicYears
   * const academicYears = await prisma.academicYear.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const academicYearWithIdOnly = await prisma.academicYear.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AcademicYearFindManyArgs>(args?: Prisma.SelectSubset<T, AcademicYearFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AcademicYear.
   * @param {AcademicYearCreateArgs} args - Arguments to create a AcademicYear.
   * @example
   * // Create one AcademicYear
   * const AcademicYear = await prisma.academicYear.create({
   *   data: {
   *     // ... data to create a AcademicYear
   *   }
   * })
   * 
   */
  create<T extends AcademicYearCreateArgs>(args: Prisma.SelectSubset<T, AcademicYearCreateArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AcademicYears.
   * @param {AcademicYearCreateManyArgs} args - Arguments to create many AcademicYears.
   * @example
   * // Create many AcademicYears
   * const academicYear = await prisma.academicYear.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AcademicYearCreateManyArgs>(args?: Prisma.SelectSubset<T, AcademicYearCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AcademicYears and returns the data saved in the database.
   * @param {AcademicYearCreateManyAndReturnArgs} args - Arguments to create many AcademicYears.
   * @example
   * // Create many AcademicYears
   * const academicYear = await prisma.academicYear.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AcademicYears and only return the `id`
   * const academicYearWithIdOnly = await prisma.academicYear.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AcademicYearCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AcademicYearCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AcademicYear.
   * @param {AcademicYearDeleteArgs} args - Arguments to delete one AcademicYear.
   * @example
   * // Delete one AcademicYear
   * const AcademicYear = await prisma.academicYear.delete({
   *   where: {
   *     // ... filter to delete one AcademicYear
   *   }
   * })
   * 
   */
  delete<T extends AcademicYearDeleteArgs>(args: Prisma.SelectSubset<T, AcademicYearDeleteArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AcademicYear.
   * @param {AcademicYearUpdateArgs} args - Arguments to update one AcademicYear.
   * @example
   * // Update one AcademicYear
   * const academicYear = await prisma.academicYear.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AcademicYearUpdateArgs>(args: Prisma.SelectSubset<T, AcademicYearUpdateArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AcademicYears.
   * @param {AcademicYearDeleteManyArgs} args - Arguments to filter AcademicYears to delete.
   * @example
   * // Delete a few AcademicYears
   * const { count } = await prisma.academicYear.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AcademicYearDeleteManyArgs>(args?: Prisma.SelectSubset<T, AcademicYearDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicYears.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AcademicYears
   * const academicYear = await prisma.academicYear.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AcademicYearUpdateManyArgs>(args: Prisma.SelectSubset<T, AcademicYearUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AcademicYears and returns the data updated in the database.
   * @param {AcademicYearUpdateManyAndReturnArgs} args - Arguments to update many AcademicYears.
   * @example
   * // Update many AcademicYears
   * const academicYear = await prisma.academicYear.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AcademicYears and only return the `id`
   * const academicYearWithIdOnly = await prisma.academicYear.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AcademicYearUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AcademicYearUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AcademicYear.
   * @param {AcademicYearUpsertArgs} args - Arguments to update or create a AcademicYear.
   * @example
   * // Update or create a AcademicYear
   * const academicYear = await prisma.academicYear.upsert({
   *   create: {
   *     // ... data to create a AcademicYear
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AcademicYear we want to update
   *   }
   * })
   */
  upsert<T extends AcademicYearUpsertArgs>(args: Prisma.SelectSubset<T, AcademicYearUpsertArgs<ExtArgs>>): Prisma.Prisma__AcademicYearClient<runtime.Types.Result.GetResult<Prisma.$AcademicYearPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AcademicYears.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearCountArgs} args - Arguments to filter AcademicYears to count.
   * @example
   * // Count the number of AcademicYears
   * const count = await prisma.academicYear.count({
   *   where: {
   *     // ... the filter for the AcademicYears we want to count
   *   }
   * })
  **/
  count<T extends AcademicYearCountArgs>(
    args?: Prisma.Subset<T, AcademicYearCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AcademicYearCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AcademicYear.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AcademicYearAggregateArgs>(args: Prisma.Subset<T, AcademicYearAggregateArgs>): Prisma.PrismaPromise<GetAcademicYearAggregateType<T>>

  /**
   * Group by AcademicYear.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AcademicYearGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AcademicYearGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AcademicYearGroupByArgs['orderBy'] }
      : { orderBy?: AcademicYearGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AcademicYearGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAcademicYearGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AcademicYear model
 */
readonly fields: AcademicYearFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AcademicYear.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AcademicYearClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sessions<T extends Prisma.AcademicYear$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYear$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tenants<T extends Prisma.AcademicYear$tenantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYear$tenantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  questionPapers<T extends Prisma.AcademicYear$questionPapersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYear$questionPapersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPaperPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  subjects<T extends Prisma.AcademicYear$subjectsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYear$subjectsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicSubjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  chapters<T extends Prisma.AcademicYear$chaptersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AcademicYear$chaptersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AcademicChapterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AcademicYear model
 */
export interface AcademicYearFieldRefs {
  readonly id: Prisma.FieldRef<"AcademicYear", 'String'>
  readonly label: Prisma.FieldRef<"AcademicYear", 'String'>
  readonly slug: Prisma.FieldRef<"AcademicYear", 'String'>
  readonly startDate: Prisma.FieldRef<"AcademicYear", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"AcademicYear", 'DateTime'>
  readonly isCurrent: Prisma.FieldRef<"AcademicYear", 'Boolean'>
  readonly isActive: Prisma.FieldRef<"AcademicYear", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AcademicYear", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AcademicYear", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AcademicYear findUnique
 */
export type AcademicYearFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter, which AcademicYear to fetch.
   */
  where: Prisma.AcademicYearWhereUniqueInput
}

/**
 * AcademicYear findUniqueOrThrow
 */
export type AcademicYearFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter, which AcademicYear to fetch.
   */
  where: Prisma.AcademicYearWhereUniqueInput
}

/**
 * AcademicYear findFirst
 */
export type AcademicYearFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter, which AcademicYear to fetch.
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicYears to fetch.
   */
  orderBy?: Prisma.AcademicYearOrderByWithRelationInput | Prisma.AcademicYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicYears.
   */
  cursor?: Prisma.AcademicYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicYears.
   */
  distinct?: Prisma.AcademicYearScalarFieldEnum | Prisma.AcademicYearScalarFieldEnum[]
}

/**
 * AcademicYear findFirstOrThrow
 */
export type AcademicYearFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter, which AcademicYear to fetch.
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicYears to fetch.
   */
  orderBy?: Prisma.AcademicYearOrderByWithRelationInput | Prisma.AcademicYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AcademicYears.
   */
  cursor?: Prisma.AcademicYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicYears.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AcademicYears.
   */
  distinct?: Prisma.AcademicYearScalarFieldEnum | Prisma.AcademicYearScalarFieldEnum[]
}

/**
 * AcademicYear findMany
 */
export type AcademicYearFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter, which AcademicYears to fetch.
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AcademicYears to fetch.
   */
  orderBy?: Prisma.AcademicYearOrderByWithRelationInput | Prisma.AcademicYearOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AcademicYears.
   */
  cursor?: Prisma.AcademicYearWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AcademicYears from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AcademicYears.
   */
  skip?: number
  distinct?: Prisma.AcademicYearScalarFieldEnum | Prisma.AcademicYearScalarFieldEnum[]
}

/**
 * AcademicYear create
 */
export type AcademicYearCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * The data needed to create a AcademicYear.
   */
  data: Prisma.XOR<Prisma.AcademicYearCreateInput, Prisma.AcademicYearUncheckedCreateInput>
}

/**
 * AcademicYear createMany
 */
export type AcademicYearCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AcademicYears.
   */
  data: Prisma.AcademicYearCreateManyInput | Prisma.AcademicYearCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicYear createManyAndReturn
 */
export type AcademicYearCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * The data used to create many AcademicYears.
   */
  data: Prisma.AcademicYearCreateManyInput | Prisma.AcademicYearCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AcademicYear update
 */
export type AcademicYearUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * The data needed to update a AcademicYear.
   */
  data: Prisma.XOR<Prisma.AcademicYearUpdateInput, Prisma.AcademicYearUncheckedUpdateInput>
  /**
   * Choose, which AcademicYear to update.
   */
  where: Prisma.AcademicYearWhereUniqueInput
}

/**
 * AcademicYear updateMany
 */
export type AcademicYearUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AcademicYears.
   */
  data: Prisma.XOR<Prisma.AcademicYearUpdateManyMutationInput, Prisma.AcademicYearUncheckedUpdateManyInput>
  /**
   * Filter which AcademicYears to update
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * Limit how many AcademicYears to update.
   */
  limit?: number
}

/**
 * AcademicYear updateManyAndReturn
 */
export type AcademicYearUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * The data used to update AcademicYears.
   */
  data: Prisma.XOR<Prisma.AcademicYearUpdateManyMutationInput, Prisma.AcademicYearUncheckedUpdateManyInput>
  /**
   * Filter which AcademicYears to update
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * Limit how many AcademicYears to update.
   */
  limit?: number
}

/**
 * AcademicYear upsert
 */
export type AcademicYearUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * The filter to search for the AcademicYear to update in case it exists.
   */
  where: Prisma.AcademicYearWhereUniqueInput
  /**
   * In case the AcademicYear found by the `where` argument doesn't exist, create a new AcademicYear with this data.
   */
  create: Prisma.XOR<Prisma.AcademicYearCreateInput, Prisma.AcademicYearUncheckedCreateInput>
  /**
   * In case the AcademicYear was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AcademicYearUpdateInput, Prisma.AcademicYearUncheckedUpdateInput>
}

/**
 * AcademicYear delete
 */
export type AcademicYearDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
  /**
   * Filter which AcademicYear to delete.
   */
  where: Prisma.AcademicYearWhereUniqueInput
}

/**
 * AcademicYear deleteMany
 */
export type AcademicYearDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AcademicYears to delete
   */
  where?: Prisma.AcademicYearWhereInput
  /**
   * Limit how many AcademicYears to delete.
   */
  limit?: number
}

/**
 * AcademicYear.sessions
 */
export type AcademicYear$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSession
   */
  select?: Prisma.AcademicSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSession
   */
  omit?: Prisma.AcademicSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSessionInclude<ExtArgs> | null
  where?: Prisma.AcademicSessionWhereInput
  orderBy?: Prisma.AcademicSessionOrderByWithRelationInput | Prisma.AcademicSessionOrderByWithRelationInput[]
  cursor?: Prisma.AcademicSessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicSessionScalarFieldEnum | Prisma.AcademicSessionScalarFieldEnum[]
}

/**
 * AcademicYear.tenants
 */
export type AcademicYear$tenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  where?: Prisma.TenantWhereInput
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  cursor?: Prisma.TenantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * AcademicYear.questionPapers
 */
export type AcademicYear$questionPapersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionPaper
   */
  select?: Prisma.QuestionPaperSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionPaper
   */
  omit?: Prisma.QuestionPaperOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionPaperInclude<ExtArgs> | null
  where?: Prisma.QuestionPaperWhereInput
  orderBy?: Prisma.QuestionPaperOrderByWithRelationInput | Prisma.QuestionPaperOrderByWithRelationInput[]
  cursor?: Prisma.QuestionPaperWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuestionPaperScalarFieldEnum | Prisma.QuestionPaperScalarFieldEnum[]
}

/**
 * AcademicYear.subjects
 */
export type AcademicYear$subjectsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicSubject
   */
  select?: Prisma.AcademicSubjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicSubject
   */
  omit?: Prisma.AcademicSubjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicSubjectInclude<ExtArgs> | null
  where?: Prisma.AcademicSubjectWhereInput
  orderBy?: Prisma.AcademicSubjectOrderByWithRelationInput | Prisma.AcademicSubjectOrderByWithRelationInput[]
  cursor?: Prisma.AcademicSubjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicSubjectScalarFieldEnum | Prisma.AcademicSubjectScalarFieldEnum[]
}

/**
 * AcademicYear.chapters
 */
export type AcademicYear$chaptersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicChapter
   */
  select?: Prisma.AcademicChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicChapter
   */
  omit?: Prisma.AcademicChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicChapterInclude<ExtArgs> | null
  where?: Prisma.AcademicChapterWhereInput
  orderBy?: Prisma.AcademicChapterOrderByWithRelationInput | Prisma.AcademicChapterOrderByWithRelationInput[]
  cursor?: Prisma.AcademicChapterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AcademicChapterScalarFieldEnum | Prisma.AcademicChapterScalarFieldEnum[]
}

/**
 * AcademicYear without action
 */
export type AcademicYearDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AcademicYear
   */
  select?: Prisma.AcademicYearSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AcademicYear
   */
  omit?: Prisma.AcademicYearOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AcademicYearInclude<ExtArgs> | null
}
