
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CqAnswer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CqAnswer
 * 
 */
export type CqAnswerModel = runtime.Types.Result.DefaultSelection<Prisma.$CqAnswerPayload>

export type AggregateCqAnswer = {
  _count: CqAnswerCountAggregateOutputType | null
  _min: CqAnswerMinAggregateOutputType | null
  _max: CqAnswerMaxAggregateOutputType | null
}

export type CqAnswerMinAggregateOutputType = {
  id: string | null
  cqId: string | null
  answerA: string | null
  answerB: string | null
  answerC: string | null
  answerD: string | null
  explanation: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CqAnswerMaxAggregateOutputType = {
  id: string | null
  cqId: string | null
  answerA: string | null
  answerB: string | null
  answerC: string | null
  answerD: string | null
  explanation: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CqAnswerCountAggregateOutputType = {
  id: number
  cqId: number
  answerA: number
  answerB: number
  answerC: number
  answerD: number
  explanation: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CqAnswerMinAggregateInputType = {
  id?: true
  cqId?: true
  answerA?: true
  answerB?: true
  answerC?: true
  answerD?: true
  explanation?: true
  createdAt?: true
  updatedAt?: true
}

export type CqAnswerMaxAggregateInputType = {
  id?: true
  cqId?: true
  answerA?: true
  answerB?: true
  answerC?: true
  answerD?: true
  explanation?: true
  createdAt?: true
  updatedAt?: true
}

export type CqAnswerCountAggregateInputType = {
  id?: true
  cqId?: true
  answerA?: true
  answerB?: true
  answerC?: true
  answerD?: true
  explanation?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CqAnswerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CqAnswer to aggregate.
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CqAnswers to fetch.
   */
  orderBy?: Prisma.CqAnswerOrderByWithRelationInput | Prisma.CqAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CqAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CqAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CqAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CqAnswers
  **/
  _count?: true | CqAnswerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CqAnswerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CqAnswerMaxAggregateInputType
}

export type GetCqAnswerAggregateType<T extends CqAnswerAggregateArgs> = {
      [P in keyof T & keyof AggregateCqAnswer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCqAnswer[P]>
    : Prisma.GetScalarType<T[P], AggregateCqAnswer[P]>
}




export type CqAnswerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CqAnswerWhereInput
  orderBy?: Prisma.CqAnswerOrderByWithAggregationInput | Prisma.CqAnswerOrderByWithAggregationInput[]
  by: Prisma.CqAnswerScalarFieldEnum[] | Prisma.CqAnswerScalarFieldEnum
  having?: Prisma.CqAnswerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CqAnswerCountAggregateInputType | true
  _min?: CqAnswerMinAggregateInputType
  _max?: CqAnswerMaxAggregateInputType
}

export type CqAnswerGroupByOutputType = {
  id: string
  cqId: string
  answerA: string | null
  answerB: string | null
  answerC: string | null
  answerD: string | null
  explanation: string | null
  createdAt: Date
  updatedAt: Date
  _count: CqAnswerCountAggregateOutputType | null
  _min: CqAnswerMinAggregateOutputType | null
  _max: CqAnswerMaxAggregateOutputType | null
}

type GetCqAnswerGroupByPayload<T extends CqAnswerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CqAnswerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CqAnswerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CqAnswerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CqAnswerGroupByOutputType[P]>
      }
    >
  >



export type CqAnswerWhereInput = {
  AND?: Prisma.CqAnswerWhereInput | Prisma.CqAnswerWhereInput[]
  OR?: Prisma.CqAnswerWhereInput[]
  NOT?: Prisma.CqAnswerWhereInput | Prisma.CqAnswerWhereInput[]
  id?: Prisma.StringFilter<"CqAnswer"> | string
  cqId?: Prisma.StringFilter<"CqAnswer"> | string
  answerA?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerB?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerC?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerD?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  explanation?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CqAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CqAnswer"> | Date | string
  cq?: Prisma.XOR<Prisma.CqScalarRelationFilter, Prisma.CqWhereInput>
}

export type CqAnswerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cqId?: Prisma.SortOrder
  answerA?: Prisma.SortOrderInput | Prisma.SortOrder
  answerB?: Prisma.SortOrderInput | Prisma.SortOrder
  answerC?: Prisma.SortOrderInput | Prisma.SortOrder
  answerD?: Prisma.SortOrderInput | Prisma.SortOrder
  explanation?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  cq?: Prisma.CqOrderByWithRelationInput
}

export type CqAnswerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  cqId?: string
  AND?: Prisma.CqAnswerWhereInput | Prisma.CqAnswerWhereInput[]
  OR?: Prisma.CqAnswerWhereInput[]
  NOT?: Prisma.CqAnswerWhereInput | Prisma.CqAnswerWhereInput[]
  answerA?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerB?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerC?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  answerD?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  explanation?: Prisma.StringNullableFilter<"CqAnswer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CqAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CqAnswer"> | Date | string
  cq?: Prisma.XOR<Prisma.CqScalarRelationFilter, Prisma.CqWhereInput>
}, "id" | "cqId">

export type CqAnswerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cqId?: Prisma.SortOrder
  answerA?: Prisma.SortOrderInput | Prisma.SortOrder
  answerB?: Prisma.SortOrderInput | Prisma.SortOrder
  answerC?: Prisma.SortOrderInput | Prisma.SortOrder
  answerD?: Prisma.SortOrderInput | Prisma.SortOrder
  explanation?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CqAnswerCountOrderByAggregateInput
  _max?: Prisma.CqAnswerMaxOrderByAggregateInput
  _min?: Prisma.CqAnswerMinOrderByAggregateInput
}

export type CqAnswerScalarWhereWithAggregatesInput = {
  AND?: Prisma.CqAnswerScalarWhereWithAggregatesInput | Prisma.CqAnswerScalarWhereWithAggregatesInput[]
  OR?: Prisma.CqAnswerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CqAnswerScalarWhereWithAggregatesInput | Prisma.CqAnswerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CqAnswer"> | string
  cqId?: Prisma.StringWithAggregatesFilter<"CqAnswer"> | string
  answerA?: Prisma.StringNullableWithAggregatesFilter<"CqAnswer"> | string | null
  answerB?: Prisma.StringNullableWithAggregatesFilter<"CqAnswer"> | string | null
  answerC?: Prisma.StringNullableWithAggregatesFilter<"CqAnswer"> | string | null
  answerD?: Prisma.StringNullableWithAggregatesFilter<"CqAnswer"> | string | null
  explanation?: Prisma.StringNullableWithAggregatesFilter<"CqAnswer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CqAnswer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CqAnswer"> | Date | string
}

export type CqAnswerCreateInput = {
  id?: string
  answerA?: string | null
  answerB?: string | null
  answerC?: string | null
  answerD?: string | null
  explanation?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cq: Prisma.CqCreateNestedOneWithoutAnswerInput
}

export type CqAnswerUncheckedCreateInput = {
  id?: string
  cqId: string
  answerA?: string | null
  answerB?: string | null
  answerC?: string | null
  answerD?: string | null
  explanation?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqAnswerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cq?: Prisma.CqUpdateOneRequiredWithoutAnswerNestedInput
}

export type CqAnswerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cqId?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqAnswerCreateManyInput = {
  id?: string
  cqId: string
  answerA?: string | null
  answerB?: string | null
  answerC?: string | null
  answerD?: string | null
  explanation?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqAnswerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqAnswerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cqId?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqAnswerNullableScalarRelationFilter = {
  is?: Prisma.CqAnswerWhereInput | null
  isNot?: Prisma.CqAnswerWhereInput | null
}

export type CqAnswerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cqId?: Prisma.SortOrder
  answerA?: Prisma.SortOrder
  answerB?: Prisma.SortOrder
  answerC?: Prisma.SortOrder
  answerD?: Prisma.SortOrder
  explanation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqAnswerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cqId?: Prisma.SortOrder
  answerA?: Prisma.SortOrder
  answerB?: Prisma.SortOrder
  answerC?: Prisma.SortOrder
  answerD?: Prisma.SortOrder
  explanation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqAnswerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cqId?: Prisma.SortOrder
  answerA?: Prisma.SortOrder
  answerB?: Prisma.SortOrder
  answerC?: Prisma.SortOrder
  answerD?: Prisma.SortOrder
  explanation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CqAnswerCreateNestedOneWithoutCqInput = {
  create?: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
  connectOrCreate?: Prisma.CqAnswerCreateOrConnectWithoutCqInput
  connect?: Prisma.CqAnswerWhereUniqueInput
}

export type CqAnswerUncheckedCreateNestedOneWithoutCqInput = {
  create?: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
  connectOrCreate?: Prisma.CqAnswerCreateOrConnectWithoutCqInput
  connect?: Prisma.CqAnswerWhereUniqueInput
}

export type CqAnswerUpdateOneWithoutCqNestedInput = {
  create?: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
  connectOrCreate?: Prisma.CqAnswerCreateOrConnectWithoutCqInput
  upsert?: Prisma.CqAnswerUpsertWithoutCqInput
  disconnect?: Prisma.CqAnswerWhereInput | boolean
  delete?: Prisma.CqAnswerWhereInput | boolean
  connect?: Prisma.CqAnswerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CqAnswerUpdateToOneWithWhereWithoutCqInput, Prisma.CqAnswerUpdateWithoutCqInput>, Prisma.CqAnswerUncheckedUpdateWithoutCqInput>
}

export type CqAnswerUncheckedUpdateOneWithoutCqNestedInput = {
  create?: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
  connectOrCreate?: Prisma.CqAnswerCreateOrConnectWithoutCqInput
  upsert?: Prisma.CqAnswerUpsertWithoutCqInput
  disconnect?: Prisma.CqAnswerWhereInput | boolean
  delete?: Prisma.CqAnswerWhereInput | boolean
  connect?: Prisma.CqAnswerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CqAnswerUpdateToOneWithWhereWithoutCqInput, Prisma.CqAnswerUpdateWithoutCqInput>, Prisma.CqAnswerUncheckedUpdateWithoutCqInput>
}

export type CqAnswerCreateWithoutCqInput = {
  id?: string
  answerA?: string | null
  answerB?: string | null
  answerC?: string | null
  answerD?: string | null
  explanation?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqAnswerUncheckedCreateWithoutCqInput = {
  id?: string
  answerA?: string | null
  answerB?: string | null
  answerC?: string | null
  answerD?: string | null
  explanation?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CqAnswerCreateOrConnectWithoutCqInput = {
  where: Prisma.CqAnswerWhereUniqueInput
  create: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
}

export type CqAnswerUpsertWithoutCqInput = {
  update: Prisma.XOR<Prisma.CqAnswerUpdateWithoutCqInput, Prisma.CqAnswerUncheckedUpdateWithoutCqInput>
  create: Prisma.XOR<Prisma.CqAnswerCreateWithoutCqInput, Prisma.CqAnswerUncheckedCreateWithoutCqInput>
  where?: Prisma.CqAnswerWhereInput
}

export type CqAnswerUpdateToOneWithWhereWithoutCqInput = {
  where?: Prisma.CqAnswerWhereInput
  data: Prisma.XOR<Prisma.CqAnswerUpdateWithoutCqInput, Prisma.CqAnswerUncheckedUpdateWithoutCqInput>
}

export type CqAnswerUpdateWithoutCqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CqAnswerUncheckedUpdateWithoutCqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  answerA?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerB?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerC?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  answerD?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  explanation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CqAnswerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cqId?: boolean
  answerA?: boolean
  answerB?: boolean
  answerC?: boolean
  answerD?: boolean
  explanation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cqAnswer"]>

export type CqAnswerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cqId?: boolean
  answerA?: boolean
  answerB?: boolean
  answerC?: boolean
  answerD?: boolean
  explanation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cqAnswer"]>

export type CqAnswerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cqId?: boolean
  answerA?: boolean
  answerB?: boolean
  answerC?: boolean
  answerD?: boolean
  explanation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cqAnswer"]>

export type CqAnswerSelectScalar = {
  id?: boolean
  cqId?: boolean
  answerA?: boolean
  answerB?: boolean
  answerC?: boolean
  answerD?: boolean
  explanation?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CqAnswerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cqId" | "answerA" | "answerB" | "answerC" | "answerD" | "explanation" | "createdAt" | "updatedAt", ExtArgs["result"]["cqAnswer"]>
export type CqAnswerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}
export type CqAnswerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}
export type CqAnswerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cq?: boolean | Prisma.CqDefaultArgs<ExtArgs>
}

export type $CqAnswerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CqAnswer"
  objects: {
    cq: Prisma.$CqPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    cqId: string
    answerA: string | null
    answerB: string | null
    answerC: string | null
    answerD: string | null
    explanation: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["cqAnswer"]>
  composites: {}
}

export type CqAnswerGetPayload<S extends boolean | null | undefined | CqAnswerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload, S>

export type CqAnswerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CqAnswerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CqAnswerCountAggregateInputType | true
  }

export interface CqAnswerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CqAnswer'], meta: { name: 'CqAnswer' } }
  /**
   * Find zero or one CqAnswer that matches the filter.
   * @param {CqAnswerFindUniqueArgs} args - Arguments to find a CqAnswer
   * @example
   * // Get one CqAnswer
   * const cqAnswer = await prisma.cqAnswer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CqAnswerFindUniqueArgs>(args: Prisma.SelectSubset<T, CqAnswerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CqAnswer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CqAnswerFindUniqueOrThrowArgs} args - Arguments to find a CqAnswer
   * @example
   * // Get one CqAnswer
   * const cqAnswer = await prisma.cqAnswer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CqAnswerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CqAnswerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CqAnswer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerFindFirstArgs} args - Arguments to find a CqAnswer
   * @example
   * // Get one CqAnswer
   * const cqAnswer = await prisma.cqAnswer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CqAnswerFindFirstArgs>(args?: Prisma.SelectSubset<T, CqAnswerFindFirstArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CqAnswer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerFindFirstOrThrowArgs} args - Arguments to find a CqAnswer
   * @example
   * // Get one CqAnswer
   * const cqAnswer = await prisma.cqAnswer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CqAnswerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CqAnswerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CqAnswers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CqAnswers
   * const cqAnswers = await prisma.cqAnswer.findMany()
   * 
   * // Get first 10 CqAnswers
   * const cqAnswers = await prisma.cqAnswer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cqAnswerWithIdOnly = await prisma.cqAnswer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CqAnswerFindManyArgs>(args?: Prisma.SelectSubset<T, CqAnswerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CqAnswer.
   * @param {CqAnswerCreateArgs} args - Arguments to create a CqAnswer.
   * @example
   * // Create one CqAnswer
   * const CqAnswer = await prisma.cqAnswer.create({
   *   data: {
   *     // ... data to create a CqAnswer
   *   }
   * })
   * 
   */
  create<T extends CqAnswerCreateArgs>(args: Prisma.SelectSubset<T, CqAnswerCreateArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CqAnswers.
   * @param {CqAnswerCreateManyArgs} args - Arguments to create many CqAnswers.
   * @example
   * // Create many CqAnswers
   * const cqAnswer = await prisma.cqAnswer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CqAnswerCreateManyArgs>(args?: Prisma.SelectSubset<T, CqAnswerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CqAnswers and returns the data saved in the database.
   * @param {CqAnswerCreateManyAndReturnArgs} args - Arguments to create many CqAnswers.
   * @example
   * // Create many CqAnswers
   * const cqAnswer = await prisma.cqAnswer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CqAnswers and only return the `id`
   * const cqAnswerWithIdOnly = await prisma.cqAnswer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CqAnswerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CqAnswerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CqAnswer.
   * @param {CqAnswerDeleteArgs} args - Arguments to delete one CqAnswer.
   * @example
   * // Delete one CqAnswer
   * const CqAnswer = await prisma.cqAnswer.delete({
   *   where: {
   *     // ... filter to delete one CqAnswer
   *   }
   * })
   * 
   */
  delete<T extends CqAnswerDeleteArgs>(args: Prisma.SelectSubset<T, CqAnswerDeleteArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CqAnswer.
   * @param {CqAnswerUpdateArgs} args - Arguments to update one CqAnswer.
   * @example
   * // Update one CqAnswer
   * const cqAnswer = await prisma.cqAnswer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CqAnswerUpdateArgs>(args: Prisma.SelectSubset<T, CqAnswerUpdateArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CqAnswers.
   * @param {CqAnswerDeleteManyArgs} args - Arguments to filter CqAnswers to delete.
   * @example
   * // Delete a few CqAnswers
   * const { count } = await prisma.cqAnswer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CqAnswerDeleteManyArgs>(args?: Prisma.SelectSubset<T, CqAnswerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CqAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CqAnswers
   * const cqAnswer = await prisma.cqAnswer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CqAnswerUpdateManyArgs>(args: Prisma.SelectSubset<T, CqAnswerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CqAnswers and returns the data updated in the database.
   * @param {CqAnswerUpdateManyAndReturnArgs} args - Arguments to update many CqAnswers.
   * @example
   * // Update many CqAnswers
   * const cqAnswer = await prisma.cqAnswer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CqAnswers and only return the `id`
   * const cqAnswerWithIdOnly = await prisma.cqAnswer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CqAnswerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CqAnswerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CqAnswer.
   * @param {CqAnswerUpsertArgs} args - Arguments to update or create a CqAnswer.
   * @example
   * // Update or create a CqAnswer
   * const cqAnswer = await prisma.cqAnswer.upsert({
   *   create: {
   *     // ... data to create a CqAnswer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CqAnswer we want to update
   *   }
   * })
   */
  upsert<T extends CqAnswerUpsertArgs>(args: Prisma.SelectSubset<T, CqAnswerUpsertArgs<ExtArgs>>): Prisma.Prisma__CqAnswerClient<runtime.Types.Result.GetResult<Prisma.$CqAnswerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CqAnswers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerCountArgs} args - Arguments to filter CqAnswers to count.
   * @example
   * // Count the number of CqAnswers
   * const count = await prisma.cqAnswer.count({
   *   where: {
   *     // ... the filter for the CqAnswers we want to count
   *   }
   * })
  **/
  count<T extends CqAnswerCountArgs>(
    args?: Prisma.Subset<T, CqAnswerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CqAnswerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CqAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CqAnswerAggregateArgs>(args: Prisma.Subset<T, CqAnswerAggregateArgs>): Prisma.PrismaPromise<GetCqAnswerAggregateType<T>>

  /**
   * Group by CqAnswer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CqAnswerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CqAnswerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CqAnswerGroupByArgs['orderBy'] }
      : { orderBy?: CqAnswerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CqAnswerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCqAnswerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CqAnswer model
 */
readonly fields: CqAnswerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CqAnswer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CqAnswerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cq<T extends Prisma.CqDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CqDefaultArgs<ExtArgs>>): Prisma.Prisma__CqClient<runtime.Types.Result.GetResult<Prisma.$CqPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CqAnswer model
 */
export interface CqAnswerFieldRefs {
  readonly id: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly cqId: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly answerA: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly answerB: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly answerC: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly answerD: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly explanation: Prisma.FieldRef<"CqAnswer", 'String'>
  readonly createdAt: Prisma.FieldRef<"CqAnswer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CqAnswer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CqAnswer findUnique
 */
export type CqAnswerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter, which CqAnswer to fetch.
   */
  where: Prisma.CqAnswerWhereUniqueInput
}

/**
 * CqAnswer findUniqueOrThrow
 */
export type CqAnswerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter, which CqAnswer to fetch.
   */
  where: Prisma.CqAnswerWhereUniqueInput
}

/**
 * CqAnswer findFirst
 */
export type CqAnswerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter, which CqAnswer to fetch.
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CqAnswers to fetch.
   */
  orderBy?: Prisma.CqAnswerOrderByWithRelationInput | Prisma.CqAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CqAnswers.
   */
  cursor?: Prisma.CqAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CqAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CqAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CqAnswers.
   */
  distinct?: Prisma.CqAnswerScalarFieldEnum | Prisma.CqAnswerScalarFieldEnum[]
}

/**
 * CqAnswer findFirstOrThrow
 */
export type CqAnswerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter, which CqAnswer to fetch.
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CqAnswers to fetch.
   */
  orderBy?: Prisma.CqAnswerOrderByWithRelationInput | Prisma.CqAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CqAnswers.
   */
  cursor?: Prisma.CqAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CqAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CqAnswers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CqAnswers.
   */
  distinct?: Prisma.CqAnswerScalarFieldEnum | Prisma.CqAnswerScalarFieldEnum[]
}

/**
 * CqAnswer findMany
 */
export type CqAnswerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter, which CqAnswers to fetch.
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CqAnswers to fetch.
   */
  orderBy?: Prisma.CqAnswerOrderByWithRelationInput | Prisma.CqAnswerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CqAnswers.
   */
  cursor?: Prisma.CqAnswerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CqAnswers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CqAnswers.
   */
  skip?: number
  distinct?: Prisma.CqAnswerScalarFieldEnum | Prisma.CqAnswerScalarFieldEnum[]
}

/**
 * CqAnswer create
 */
export type CqAnswerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * The data needed to create a CqAnswer.
   */
  data: Prisma.XOR<Prisma.CqAnswerCreateInput, Prisma.CqAnswerUncheckedCreateInput>
}

/**
 * CqAnswer createMany
 */
export type CqAnswerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CqAnswers.
   */
  data: Prisma.CqAnswerCreateManyInput | Prisma.CqAnswerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CqAnswer createManyAndReturn
 */
export type CqAnswerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * The data used to create many CqAnswers.
   */
  data: Prisma.CqAnswerCreateManyInput | Prisma.CqAnswerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CqAnswer update
 */
export type CqAnswerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * The data needed to update a CqAnswer.
   */
  data: Prisma.XOR<Prisma.CqAnswerUpdateInput, Prisma.CqAnswerUncheckedUpdateInput>
  /**
   * Choose, which CqAnswer to update.
   */
  where: Prisma.CqAnswerWhereUniqueInput
}

/**
 * CqAnswer updateMany
 */
export type CqAnswerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CqAnswers.
   */
  data: Prisma.XOR<Prisma.CqAnswerUpdateManyMutationInput, Prisma.CqAnswerUncheckedUpdateManyInput>
  /**
   * Filter which CqAnswers to update
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * Limit how many CqAnswers to update.
   */
  limit?: number
}

/**
 * CqAnswer updateManyAndReturn
 */
export type CqAnswerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * The data used to update CqAnswers.
   */
  data: Prisma.XOR<Prisma.CqAnswerUpdateManyMutationInput, Prisma.CqAnswerUncheckedUpdateManyInput>
  /**
   * Filter which CqAnswers to update
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * Limit how many CqAnswers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CqAnswer upsert
 */
export type CqAnswerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * The filter to search for the CqAnswer to update in case it exists.
   */
  where: Prisma.CqAnswerWhereUniqueInput
  /**
   * In case the CqAnswer found by the `where` argument doesn't exist, create a new CqAnswer with this data.
   */
  create: Prisma.XOR<Prisma.CqAnswerCreateInput, Prisma.CqAnswerUncheckedCreateInput>
  /**
   * In case the CqAnswer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CqAnswerUpdateInput, Prisma.CqAnswerUncheckedUpdateInput>
}

/**
 * CqAnswer delete
 */
export type CqAnswerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
  /**
   * Filter which CqAnswer to delete.
   */
  where: Prisma.CqAnswerWhereUniqueInput
}

/**
 * CqAnswer deleteMany
 */
export type CqAnswerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CqAnswers to delete
   */
  where?: Prisma.CqAnswerWhereInput
  /**
   * Limit how many CqAnswers to delete.
   */
  limit?: number
}

/**
 * CqAnswer without action
 */
export type CqAnswerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CqAnswer
   */
  select?: Prisma.CqAnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CqAnswer
   */
  omit?: Prisma.CqAnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CqAnswerInclude<ExtArgs> | null
}
