export enum RESIDENT_STATUS {
  RESIDENT = "RESIDENT",
  NON_RESIDENT = "NON_RESIDENT",
}

export enum MARITAL_STATUS {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  WIDOWED = "WIDOWED",
  DIVORCED = "DIVORCED",
}

